// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// LeadFields provides type-safe field selection for Lead
type LeadFields struct {
	selection *builder.FieldSelection
}

// NewLeadFields creates a new LeadFields selector
func NewLeadFields(selection *builder.FieldSelection) *LeadFields {
	return &LeadFields{selection: selection}
}

// ID selects the id field
func (f *LeadFields) ID() *LeadFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *LeadFields) CreatedAt() *LeadFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *LeadFields) UpdatedAt() *LeadFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *LeadFields) Name() *LeadFields {
	f.selection.AddField("name")
	return f
}

// Email selects the email field
func (f *LeadFields) Email() *LeadFields {
	f.selection.AddField("email")
	return f
}

// Phone selects the phone field
func (f *LeadFields) Phone() *LeadFields {
	f.selection.AddField("phone")
	return f
}

// Company selects the company field
func (f *LeadFields) Company() *LeadFields {
	f.selection.AddField("company")
	return f
}

// IP selects the ip field
func (f *LeadFields) IP() *LeadFields {
	f.selection.AddField("ip")
	return f
}

// GuestUserID selects the guestUserID field
func (f *LeadFields) GuestUserID() *LeadFields {
	f.selection.AddField("guestUserID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *LeadFields) ChatbotID() *LeadFields {
	f.selection.AddField("chatbotID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *LeadFields) WorkspaceID() *LeadFields {
	f.selection.AddField("workspaceID")
	return f
}
