// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// BillingPlanFeatureEdgeFields provides type-safe field selection for BillingPlanFeatureEdge
type BillingPlanFeatureEdgeFields struct {
	selection *builder.FieldSelection
}

// NewBillingPlanFeatureEdgeFields creates a new BillingPlanFeatureEdgeFields selector
func NewBillingPlanFeatureEdgeFields(selection *builder.FieldSelection) *BillingPlanFeatureEdgeFields {
	return &BillingPlanFeatureEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *BillingPlanFeatureEdgeFields) Node(selector func(*BillingPlanFeatureFields)) *BillingPlanFeatureEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanFeatureFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *BillingPlanFeatureEdgeFields) Cursor() *BillingPlanFeatureEdgeFields {
	f.selection.AddField("cursor")
	return f
}
