// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// LeadConnectionFields provides type-safe field selection for LeadConnection
type LeadConnectionFields struct {
	selection *builder.FieldSelection
}

// NewLeadConnectionFields creates a new LeadConnectionFields selector
func NewLeadConnectionFields(selection *builder.FieldSelection) *LeadConnectionFields {
	return &LeadConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *LeadConnectionFields) Edges(selector func(*LeadEdgeFields)) *LeadConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewLeadEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *LeadConnectionFields) PageInfo(selector func(*PageInfoFields)) *LeadConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *LeadConnectionFields) TotalCount() *LeadConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
