// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// CWorkspaceFeatureLimitEdgeFields provides type-safe field selection for CWorkspaceFeatureLimitEdge
type CWorkspaceFeatureLimitEdgeFields struct {
	selection *builder.FieldSelection
}

// NewCWorkspaceFeatureLimitEdgeFields creates a new CWorkspaceFeatureLimitEdgeFields selector
func NewCWorkspaceFeatureLimitEdgeFields(selection *builder.FieldSelection) *CWorkspaceFeatureLimitEdgeFields {
	return &CWorkspaceFeatureLimitEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *CWorkspaceFeatureLimitEdgeFields) Node(selector func(*CWorkspaceFeatureLimitFields)) *CWorkspaceFeatureLimitEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewCWorkspaceFeatureLimitFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *CWorkspaceFeatureLimitEdgeFields) Cursor() *CWorkspaceFeatureLimitEdgeFields {
	f.selection.AddField("cursor")
	return f
}
