// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// FuncToolLogConnectionFields provides type-safe field selection for FuncToolLogConnection
type FuncToolLogConnectionFields struct {
	selection *builder.FieldSelection
}

// NewFuncToolLogConnectionFields creates a new FuncToolLogConnectionFields selector
func NewFuncToolLogConnectionFields(selection *builder.FieldSelection) *FuncToolLogConnectionFields {
	return &FuncToolLogConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *FuncToolLogConnectionFields) Edges(selector func(*FuncToolLogEdgeFields)) *FuncToolLogConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolLogEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *FuncToolLogConnectionFields) PageInfo(selector func(*PageInfoFields)) *FuncToolLogConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *FuncToolLogConnectionFields) TotalCount() *FuncToolLogConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
