// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// BillingFeatureEdgeFields provides type-safe field selection for BillingFeatureEdge
type BillingFeatureEdgeFields struct {
	selection *builder.FieldSelection
}

// NewBillingFeatureEdgeFields creates a new BillingFeatureEdgeFields selector
func NewBillingFeatureEdgeFields(selection *builder.FieldSelection) *BillingFeatureEdgeFields {
	return &BillingFeatureEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *BillingFeatureEdgeFields) Node(selector func(*BillingFeatureFields)) *BillingFeatureEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingFeatureFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *BillingFeatureEdgeFields) Cursor() *BillingFeatureEdgeFields {
	f.selection.AddField("cursor")
	return f
}
