// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ChannelUserFields provides type-safe field selection for ChannelUser
type ChannelUserFields struct {
	selection *builder.FieldSelection
}

// NewChannelUserFields creates a new ChannelUserFields selector
func NewChannelUserFields(selection *builder.FieldSelection) *ChannelUserFields {
	return &ChannelUserFields{selection: selection}
}

// ID selects the id field
func (f *ChannelUserFields) ID() *ChannelUserFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *ChannelUserFields) CreatedAt() *ChannelUserFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *ChannelUserFields) UpdatedAt() *ChannelUserFields {
	f.selection.AddField("updatedAt")
	return f
}

// UserID selects the userID field
func (f *ChannelUserFields) UserID() *ChannelUserFields {
	f.selection.AddField("userID")
	return f
}

// ChannelID selects the channelID field
func (f *ChannelUserFields) ChannelID() *ChannelUserFields {
	f.selection.AddField("channelID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *ChannelUserFields) WorkspaceID() *ChannelUserFields {
	f.selection.AddField("workspaceID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *ChannelUserFields) ChatbotID() *ChannelUserFields {
	f.selection.AddField("chatbotID")
	return f
}

// User selects the user field with nested selection
func (f *ChannelUserFields) User(selector func(*UserFields)) *ChannelUserFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("user", child)
	return f
}

// Channel selects the channel field with nested selection
func (f *ChannelUserFields) Channel(selector func(*ChannelFields)) *ChannelUserFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChannelFields(child))
	}
	f.selection.AddChild("channel", child)
	return f
}
