// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// BillingPlanFields provides type-safe field selection for BillingPlan
type BillingPlanFields struct {
	selection *builder.FieldSelection
}

// NewBillingPlanFields creates a new BillingPlanFields selector
func NewBillingPlanFields(selection *builder.FieldSelection) *BillingPlanFields {
	return &BillingPlanFields{selection: selection}
}

// ID selects the id field
func (f *BillingPlanFields) ID() *BillingPlanFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *BillingPlanFields) CreatedAt() *BillingPlanFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *BillingPlanFields) UpdatedAt() *BillingPlanFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *BillingPlanFields) Name() *BillingPlanFields {
	f.selection.AddField("name")
	return f
}

// GroupName selects the groupName field
func (f *BillingPlanFields) GroupName() *BillingPlanFields {
	f.selection.AddField("groupName")
	return f
}

// Description selects the description field
func (f *BillingPlanFields) Description() *BillingPlanFields {
	f.selection.AddField("description")
	return f
}

// IsActive selects the isActive field
func (f *BillingPlanFields) IsActive() *BillingPlanFields {
	f.selection.AddField("isActive")
	return f
}

// StripeProductID selects the stripeProductID field
func (f *BillingPlanFields) StripeProductID() *BillingPlanFields {
	f.selection.AddField("stripeProductID")
	return f
}

// IsMultiQty selects the isMultiQty field
func (f *BillingPlanFields) IsMultiQty() *BillingPlanFields {
	f.selection.AddField("isMultiQty")
	return f
}

// MaxQty selects the maxQty field
func (f *BillingPlanFields) MaxQty() *BillingPlanFields {
	f.selection.AddField("maxQty")
	return f
}

// IsCustom selects the isCustom field
func (f *BillingPlanFields) IsCustom() *BillingPlanFields {
	f.selection.AddField("isCustom")
	return f
}

// CustomPriceID selects the customPriceID field
func (f *BillingPlanFields) CustomPriceID() *BillingPlanFields {
	f.selection.AddField("customPriceID")
	return f
}

// PlanType selects the planType field
func (f *BillingPlanFields) PlanType() *BillingPlanFields {
	f.selection.AddField("planType")
	return f
}

// HasAnnual selects the hasAnnual field
func (f *BillingPlanFields) HasAnnual() *BillingPlanFields {
	f.selection.AddField("hasAnnual")
	return f
}

// StripePriceID selects the stripePriceID field
func (f *BillingPlanFields) StripePriceID() *BillingPlanFields {
	f.selection.AddField("stripePriceID")
	return f
}

// StripePriceIdannual selects the stripePriceIDAnnual field
func (f *BillingPlanFields) StripePriceIdannual() *BillingPlanFields {
	f.selection.AddField("stripePriceIDAnnual")
	return f
}

// Amount selects the amount field
func (f *BillingPlanFields) Amount() *BillingPlanFields {
	f.selection.AddField("amount")
	return f
}

// AmountAnnual selects the amountAnnual field
func (f *BillingPlanFields) AmountAnnual() *BillingPlanFields {
	f.selection.AddField("amountAnnual")
	return f
}

// Features selects the features field
func (f *BillingPlanFields) Features() *BillingPlanFields {
	f.selection.AddField("features")
	return f
}

// SortOrder selects the sortOrder field
func (f *BillingPlanFields) SortOrder() *BillingPlanFields {
	f.selection.AddField("sortOrder")
	return f
}

// BillingPlanFeatures selects the billingPlanFeatures field with nested selection
func (f *BillingPlanFields) BillingPlanFeatures(selector func(*BillingPlanFeatureFields)) *BillingPlanFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanFeatureFields(child))
	}
	f.selection.AddChild("billingPlanFeatures", child)
	return f
}
