// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ChatbotToolConnectionFields provides type-safe field selection for ChatbotToolConnection
type ChatbotToolConnectionFields struct {
	selection *builder.FieldSelection
}

// NewChatbotToolConnectionFields creates a new ChatbotToolConnectionFields selector
func NewChatbotToolConnectionFields(selection *builder.FieldSelection) *ChatbotToolConnectionFields {
	return &ChatbotToolConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ChatbotToolConnectionFields) Edges(selector func(*ChatbotToolEdgeFields)) *ChatbotToolConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotToolEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ChatbotToolConnectionFields) PageInfo(selector func(*PageInfoFields)) *ChatbotToolConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ChatbotToolConnectionFields) TotalCount() *ChatbotToolConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
