// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// AiModelFields provides type-safe field selection for AiModel
type AiModelFields struct {
	selection *builder.FieldSelection
}

// NewAiModelFields creates a new AiModelFields selector
func NewAiModelFields(selection *builder.FieldSelection) *AiModelFields {
	return &AiModelFields{selection: selection}
}

// ID selects the id field
func (f *AiModelFields) ID() *AiModelFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *AiModelFields) CreatedAt() *AiModelFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *AiModelFields) UpdatedAt() *AiModelFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *AiModelFields) Name() *AiModelFields {
	f.selection.AddField("name")
	return f
}

// ProviderName selects the providerName field
func (f *AiModelFields) ProviderName() *AiModelFields {
	f.selection.AddField("providerName")
	return f
}

// ModelID selects the modelID field
func (f *AiModelFields) ModelID() *AiModelFields {
	f.selection.AddField("modelID")
	return f
}

// BaseURL selects the baseURL field
func (f *AiModelFields) BaseURL() *AiModelFields {
	f.selection.AddField("baseURL")
	return f
}

// APIKey selects the apiKey field
func (f *AiModelFields) APIKey() *AiModelFields {
	f.selection.AddField("apiKey")
	return f
}

// OrgID selects the orgID field
func (f *AiModelFields) OrgID() *AiModelFields {
	f.selection.AddField("orgID")
	return f
}

// Descr selects the descr field
func (f *AiModelFields) Descr() *AiModelFields {
	f.selection.AddField("descr")
	return f
}

// Status selects the status field
func (f *AiModelFields) Status() *AiModelFields {
	f.selection.AddField("status")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *AiModelFields) WorkspaceID() *AiModelFields {
	f.selection.AddField("workspaceID")
	return f
}

// HasChat selects the hasChat field
func (f *AiModelFields) HasChat() *AiModelFields {
	f.selection.AddField("hasChat")
	return f
}

// HasEmbeddings selects the hasEmbeddings field
func (f *AiModelFields) HasEmbeddings() *AiModelFields {
	f.selection.AddField("hasEmbeddings")
	return f
}

// IsWildai selects the isWildai field
func (f *AiModelFields) IsWildai() *AiModelFields {
	f.selection.AddField("isWildai")
	return f
}

// IntProviderName selects the intProviderName field
func (f *AiModelFields) IntProviderName() *AiModelFields {
	f.selection.AddField("intProviderName")
	return f
}

// IntBaseURL selects the intBaseURL field
func (f *AiModelFields) IntBaseURL() *AiModelFields {
	f.selection.AddField("intBaseURL")
	return f
}

// IntApikey selects the intAPIKey field
func (f *AiModelFields) IntApikey() *AiModelFields {
	f.selection.AddField("intAPIKey")
	return f
}

// IntOrgID selects the intOrgID field
func (f *AiModelFields) IntOrgID() *AiModelFields {
	f.selection.AddField("intOrgID")
	return f
}

// IntModelID selects the intModelID field
func (f *AiModelFields) IntModelID() *AiModelFields {
	f.selection.AddField("intModelID")
	return f
}

// MaxDims selects the maxDims field
func (f *AiModelFields) MaxDims() *AiModelFields {
	f.selection.AddField("maxDims")
	return f
}

// MaxTokens selects the maxTokens field
func (f *AiModelFields) MaxTokens() *AiModelFields {
	f.selection.AddField("maxTokens")
	return f
}

// Chatbots selects the chatbots field with nested selection
func (f *AiModelFields) Chatbots(selector func(*ChatbotFields)) *AiModelFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbots", child)
	return f
}

// FuncTools selects the funcTools field with nested selection
func (f *AiModelFields) FuncTools(selector func(*FuncToolFields)) *AiModelFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolFields(child))
	}
	f.selection.AddChild("funcTools", child)
	return f
}

// ItemGroups selects the itemGroups field with nested selection
func (f *AiModelFields) ItemGroups(selector func(*ItemGroupFields)) *AiModelFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewItemGroupFields(child))
	}
	f.selection.AddChild("itemGroups", child)
	return f
}
