// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// FolderFields provides type-safe field selection for Folder
type FolderFields struct {
	selection *builder.FieldSelection
}

// NewFolderFields creates a new FolderFields selector
func NewFolderFields(selection *builder.FieldSelection) *FolderFields {
	return &FolderFields{selection: selection}
}

// ID selects the id field
func (f *FolderFields) ID() *FolderFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *FolderFields) CreatedAt() *FolderFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *FolderFields) UpdatedAt() *FolderFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *FolderFields) Name() *FolderFields {
	f.selection.AddField("name")
	return f
}

// ChatbotID selects the chatbotID field
func (f *FolderFields) ChatbotID() *FolderFields {
	f.selection.AddField("chatbotID")
	return f
}

// OwnerID selects the ownerID field
func (f *FolderFields) OwnerID() *FolderFields {
	f.selection.AddField("ownerID")
	return f
}

// Position selects the position field
func (f *FolderFields) Position() *FolderFields {
	f.selection.AddField("position")
	return f
}

// Channels selects the channels field with nested selection
func (f *FolderFields) Channels(selector func(*ChannelFields)) *FolderFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChannelFields(child))
	}
	f.selection.AddChild("channels", child)
	return f
}

// Chatbot selects the chatbot field with nested selection
func (f *FolderFields) Chatbot(selector func(*ChatbotFields)) *FolderFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbot", child)
	return f
}

// Owner selects the owner field with nested selection
func (f *FolderFields) Owner(selector func(*UserFields)) *FolderFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("owner", child)
	return f
}

// ChannelCount selects the channelCount field
func (f *FolderFields) ChannelCount() *FolderFields {
	f.selection.AddField("channelCount")
	return f
}
