// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ChannelFields provides type-safe field selection for Channel
type ChannelFields struct {
	selection *builder.FieldSelection
}

// NewChannelFields creates a new ChannelFields selector
func NewChannelFields(selection *builder.FieldSelection) *ChannelFields {
	return &ChannelFields{selection: selection}
}

// ID selects the id field
func (f *ChannelFields) ID() *ChannelFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *ChannelFields) CreatedAt() *ChannelFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *ChannelFields) UpdatedAt() *ChannelFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *ChannelFields) Name() *ChannelFields {
	f.selection.AddField("name")
	return f
}

// IsPublic selects the isPublic field
func (f *ChannelFields) IsPublic() *ChannelFields {
	f.selection.AddField("isPublic")
	return f
}

// GuestID selects the guestID field
func (f *ChannelFields) GuestID() *ChannelFields {
	f.selection.AddField("guestID")
	return f
}

// OwnerID selects the ownerID field
func (f *ChannelFields) OwnerID() *ChannelFields {
	f.selection.AddField("ownerID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *ChannelFields) WorkspaceID() *ChannelFields {
	f.selection.AddField("workspaceID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *ChannelFields) ChatbotID() *ChannelFields {
	f.selection.AddField("chatbotID")
	return f
}

// FolderID selects the folderID field
func (f *ChannelFields) FolderID() *ChannelFields {
	f.selection.AddField("folderID")
	return f
}

// Messages selects the messages field with nested selection
func (f *ChannelFields) Messages(selector func(*MessageConnectionFields)) *ChannelFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewMessageConnectionFields(child))
	}
	f.selection.AddChild("messages", child)
	return f
}

// Users selects the users field with nested selection
func (f *ChannelFields) Users(selector func(*UserConnectionFields)) *ChannelFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewUserConnectionFields(child))
	}
	f.selection.AddChild("users", child)
	return f
}

// Owner selects the owner field with nested selection
func (f *ChannelFields) Owner(selector func(*UserFields)) *ChannelFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("owner", child)
	return f
}

// Chatbot selects the chatbot field with nested selection
func (f *ChannelFields) Chatbot(selector func(*ChatbotFields)) *ChannelFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbot", child)
	return f
}

// Folder selects the folder field with nested selection
func (f *ChannelFields) Folder(selector func(*FolderFields)) *ChannelFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewFolderFields(child))
	}
	f.selection.AddChild("folder", child)
	return f
}

// ChannelUsers selects the channelUsers field with nested selection
func (f *ChannelFields) ChannelUsers(selector func(*ChannelUserConnectionFields)) *ChannelFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChannelUserConnectionFields(child))
	}
	f.selection.AddChild("channelUsers", child)
	return f
}
