// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// FolderEdgeFields provides type-safe field selection for FolderEdge
type FolderEdgeFields struct {
	selection *builder.FieldSelection
}

// NewFolderEdgeFields creates a new FolderEdgeFields selector
func NewFolderEdgeFields(selection *builder.FieldSelection) *FolderEdgeFields {
	return &FolderEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *FolderEdgeFields) Node(selector func(*FolderFields)) *FolderEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewFolderFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *FolderEdgeFields) Cursor() *FolderEdgeFields {
	f.selection.AddField("cursor")
	return f
}
