// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ItemGroupSourceConnectionFields provides type-safe field selection for ItemGroupSourceConnection
type ItemGroupSourceConnectionFields struct {
	selection *builder.FieldSelection
}

// NewItemGroupSourceConnectionFields creates a new ItemGroupSourceConnectionFields selector
func NewItemGroupSourceConnectionFields(selection *builder.FieldSelection) *ItemGroupSourceConnectionFields {
	return &ItemGroupSourceConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ItemGroupSourceConnectionFields) Edges(selector func(*ItemGroupSourceEdgeFields)) *ItemGroupSourceConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewItemGroupSourceEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ItemGroupSourceConnectionFields) PageInfo(selector func(*PageInfoFields)) *ItemGroupSourceConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ItemGroupSourceConnectionFields) TotalCount() *ItemGroupSourceConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
