// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// UserFields provides type-safe field selection for User
type UserFields struct {
	selection *builder.FieldSelection
}

// NewUserFields creates a new UserFields selector
func NewUserFields(selection *builder.FieldSelection) *UserFields {
	return &UserFields{selection: selection}
}

// ID selects the id field
func (f *UserFields) ID() *UserFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *UserFields) CreatedAt() *UserFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *UserFields) UpdatedAt() *UserFields {
	f.selection.AddField("updatedAt")
	return f
}

// Type selects the type field
func (f *UserFields) Type() *UserFields {
	f.selection.AddField("type")
	return f
}

// ExtUserID selects the extUserID field
func (f *UserFields) ExtUserID() *UserFields {
	f.selection.AddField("extUserID")
	return f
}

// FirstName selects the firstName field
func (f *UserFields) FirstName() *UserFields {
	f.selection.AddField("firstName")
	return f
}

// LastName selects the lastName field
func (f *UserFields) LastName() *UserFields {
	f.selection.AddField("lastName")
	return f
}

// Email selects the email field
func (f *UserFields) Email() *UserFields {
	f.selection.AddField("email")
	return f
}

// IP selects the ip field
func (f *UserFields) IP() *UserFields {
	f.selection.AddField("ip")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *UserFields) WorkspaceID() *UserFields {
	f.selection.AddField("workspaceID")
	return f
}

// MyChannels selects the myChannels field with nested selection
func (f *UserFields) MyChannels(selector func(*ChannelFields)) *UserFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChannelFields(child))
	}
	f.selection.AddChild("myChannels", child)
	return f
}

// Channels selects the channels field with nested selection
func (f *UserFields) Channels(selector func(*ChannelFields)) *UserFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChannelFields(child))
	}
	f.selection.AddChild("channels", child)
	return f
}

// Messages selects the messages field with nested selection
func (f *UserFields) Messages(selector func(*MessageFields)) *UserFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewMessageFields(child))
	}
	f.selection.AddChild("messages", child)
	return f
}

// Chatbots selects the chatbots field with nested selection
func (f *UserFields) Chatbots(selector func(*ChatbotFields)) *UserFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbots", child)
	return f
}

// Folders selects the folders field with nested selection
func (f *UserFields) Folders(selector func(*FolderFields)) *UserFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewFolderFields(child))
	}
	f.selection.AddChild("folders", child)
	return f
}

// ChannelUsers selects the channelUsers field with nested selection
func (f *UserFields) ChannelUsers(selector func(*ChannelUserFields)) *UserFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChannelUserFields(child))
	}
	f.selection.AddChild("channelUsers", child)
	return f
}

// ChatbotUsers selects the chatbotUsers field with nested selection
func (f *UserFields) ChatbotUsers(selector func(*ChatbotUserFields)) *UserFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotUserFields(child))
	}
	f.selection.AddChild("chatbotUsers", child)
	return f
}
