// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ChannelUserConnectionFields provides type-safe field selection for ChannelUserConnection
type ChannelUserConnectionFields struct {
	selection *builder.FieldSelection
}

// NewChannelUserConnectionFields creates a new ChannelUserConnectionFields selector
func NewChannelUserConnectionFields(selection *builder.FieldSelection) *ChannelUserConnectionFields {
	return &ChannelUserConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ChannelUserConnectionFields) Edges(selector func(*ChannelUserEdgeFields)) *ChannelUserConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChannelUserEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ChannelUserConnectionFields) PageInfo(selector func(*PageInfoFields)) *ChannelUserConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ChannelUserConnectionFields) TotalCount() *ChannelUserConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
