// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ItemGroupConnectionFields provides type-safe field selection for ItemGroupConnection
type ItemGroupConnectionFields struct {
	selection *builder.FieldSelection
}

// NewItemGroupConnectionFields creates a new ItemGroupConnectionFields selector
func NewItemGroupConnectionFields(selection *builder.FieldSelection) *ItemGroupConnectionFields {
	return &ItemGroupConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ItemGroupConnectionFields) Edges(selector func(*ItemGroupEdgeFields)) *ItemGroupConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewItemGroupEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ItemGroupConnectionFields) PageInfo(selector func(*PageInfoFields)) *ItemGroupConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ItemGroupConnectionFields) TotalCount() *ItemGroupConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
