// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// FuncToolConnectionFields provides type-safe field selection for FuncToolConnection
type FuncToolConnectionFields struct {
	selection *builder.FieldSelection
}

// NewFuncToolConnectionFields creates a new FuncToolConnectionFields selector
func NewFuncToolConnectionFields(selection *builder.FieldSelection) *FuncToolConnectionFields {
	return &FuncToolConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *FuncToolConnectionFields) Edges(selector func(*FuncToolEdgeFields)) *FuncToolConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *FuncToolConnectionFields) PageInfo(selector func(*PageInfoFields)) *FuncToolConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *FuncToolConnectionFields) TotalCount() *FuncToolConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
