// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ChatbotConnectionFields provides type-safe field selection for ChatbotConnection
type ChatbotConnectionFields struct {
	selection *builder.FieldSelection
}

// NewChatbotConnectionFields creates a new ChatbotConnectionFields selector
func NewChatbotConnectionFields(selection *builder.FieldSelection) *ChatbotConnectionFields {
	return &ChatbotConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ChatbotConnectionFields) Edges(selector func(*ChatbotEdgeFields)) *ChatbotConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ChatbotConnectionFields) PageInfo(selector func(*PageInfoFields)) *ChatbotConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ChatbotConnectionFields) TotalCount() *ChatbotConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
