// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// CWorkspaceFeatureLimitConnectionFields provides type-safe field selection for CWorkspaceFeatureLimitConnection
type CWorkspaceFeatureLimitConnectionFields struct {
	selection *builder.FieldSelection
}

// NewCWorkspaceFeatureLimitConnectionFields creates a new CWorkspaceFeatureLimitConnectionFields selector
func NewCWorkspaceFeatureLimitConnectionFields(selection *builder.FieldSelection) *CWorkspaceFeatureLimitConnectionFields {
	return &CWorkspaceFeatureLimitConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *CWorkspaceFeatureLimitConnectionFields) Edges(selector func(*CWorkspaceFeatureLimitEdgeFields)) *CWorkspaceFeatureLimitConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewCWorkspaceFeatureLimitEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *CWorkspaceFeatureLimitConnectionFields) PageInfo(selector func(*PageInfoFields)) *CWorkspaceFeatureLimitConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *CWorkspaceFeatureLimitConnectionFields) TotalCount() *CWorkspaceFeatureLimitConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
