// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ItemEdgeFields provides type-safe field selection for ItemEdge
type ItemEdgeFields struct {
	selection *builder.FieldSelection
}

// NewItemEdgeFields creates a new ItemEdgeFields selector
func NewItemEdgeFields(selection *builder.FieldSelection) *ItemEdgeFields {
	return &ItemEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ItemEdgeFields) Node(selector func(*ItemFields)) *ItemEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewItemFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ItemEdgeFields) Cursor() *ItemEdgeFields {
	f.selection.AddField("cursor")
	return f
}
