// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ChannelEdgeFields provides type-safe field selection for ChannelEdge
type ChannelEdgeFields struct {
	selection *builder.FieldSelection
}

// NewChannelEdgeFields creates a new ChannelEdgeFields selector
func NewChannelEdgeFields(selection *builder.FieldSelection) *ChannelEdgeFields {
	return &ChannelEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ChannelEdgeFields) Node(selector func(*ChannelFields)) *ChannelEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChannelFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ChannelEdgeFields) Cursor() *ChannelEdgeFields {
	f.selection.AddField("cursor")
	return f
}
