// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// CWorkspaceSubConnectionFields provides type-safe field selection for CWorkspaceSubConnection
type CWorkspaceSubConnectionFields struct {
	selection *builder.FieldSelection
}

// NewCWorkspaceSubConnectionFields creates a new CWorkspaceSubConnectionFields selector
func NewCWorkspaceSubConnectionFields(selection *builder.FieldSelection) *CWorkspaceSubConnectionFields {
	return &CWorkspaceSubConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *CWorkspaceSubConnectionFields) Edges(selector func(*CWorkspaceSubEdgeFields)) *CWorkspaceSubConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewCWorkspaceSubEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *CWorkspaceSubConnectionFields) PageInfo(selector func(*PageInfoFields)) *CWorkspaceSubConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *CWorkspaceSubConnectionFields) TotalCount() *CWorkspaceSubConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
