// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// WorkspaceDetailFields provides type-safe field selection for WorkspaceDetail
type WorkspaceDetailFields struct {
	selection *builder.FieldSelection
}

// NewWorkspaceDetailFields creates a new WorkspaceDetailFields selector
func NewWorkspaceDetailFields(selection *builder.FieldSelection) *WorkspaceDetailFields {
	return &WorkspaceDetailFields{selection: selection}
}

// ID selects the id field
func (f *WorkspaceDetailFields) ID() *WorkspaceDetailFields {
	f.selection.AddField("id")
	return f
}

// Name selects the name field
func (f *WorkspaceDetailFields) Name() *WorkspaceDetailFields {
	f.selection.AddField("name")
	return f
}

// TotalAgents selects the totalAgents field
func (f *WorkspaceDetailFields) TotalAgents() *WorkspaceDetailFields {
	f.selection.AddField("totalAgents")
	return f
}

// TotalDatasets selects the totalDatasets field
func (f *WorkspaceDetailFields) TotalDatasets() *WorkspaceDetailFields {
	f.selection.AddField("totalDatasets")
	return f
}

// TotalUsers selects the totalUsers field
func (f *WorkspaceDetailFields) TotalUsers() *WorkspaceDetailFields {
	f.selection.AddField("totalUsers")
	return f
}

// TotalChannels selects the totalChannels field
func (f *WorkspaceDetailFields) TotalChannels() *WorkspaceDetailFields {
	f.selection.AddField("totalChannels")
	return f
}

// TotalMessages selects the totalMessages field
func (f *WorkspaceDetailFields) TotalMessages() *WorkspaceDetailFields {
	f.selection.AddField("totalMessages")
	return f
}
