// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ChannelConnectionFields provides type-safe field selection for ChannelConnection
type ChannelConnectionFields struct {
	selection *builder.FieldSelection
}

// NewChannelConnectionFields creates a new ChannelConnectionFields selector
func NewChannelConnectionFields(selection *builder.FieldSelection) *ChannelConnectionFields {
	return &ChannelConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ChannelConnectionFields) Edges(selector func(*ChannelEdgeFields)) *ChannelConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChannelEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ChannelConnectionFields) PageInfo(selector func(*PageInfoFields)) *ChannelConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ChannelConnectionFields) TotalCount() *ChannelConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
