// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// BillingPlanWspaceEdgeFields provides type-safe field selection for BillingPlanWspaceEdge
type BillingPlanWspaceEdgeFields struct {
	selection *builder.FieldSelection
}

// NewBillingPlanWspaceEdgeFields creates a new BillingPlanWspaceEdgeFields selector
func NewBillingPlanWspaceEdgeFields(selection *builder.FieldSelection) *BillingPlanWspaceEdgeFields {
	return &BillingPlanWspaceEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *BillingPlanWspaceEdgeFields) Node(selector func(*BillingPlanWspaceFields)) *BillingPlanWspaceEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanWspaceFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *BillingPlanWspaceEdgeFields) Cursor() *BillingPlanWspaceEdgeFields {
	f.selection.AddField("cursor")
	return f
}
