// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ItemGroupSourceEdgeFields provides type-safe field selection for ItemGroupSourceEdge
type ItemGroupSourceEdgeFields struct {
	selection *builder.FieldSelection
}

// NewItemGroupSourceEdgeFields creates a new ItemGroupSourceEdgeFields selector
func NewItemGroupSourceEdgeFields(selection *builder.FieldSelection) *ItemGroupSourceEdgeFields {
	return &ItemGroupSourceEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ItemGroupSourceEdgeFields) Node(selector func(*ItemGroupSourceFields)) *ItemGroupSourceEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewItemGroupSourceFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ItemGroupSourceEdgeFields) Cursor() *ItemGroupSourceEdgeFields {
	f.selection.AddField("cursor")
	return f
}
