// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// FolderConnectionFields provides type-safe field selection for FolderConnection
type FolderConnectionFields struct {
	selection *builder.FieldSelection
}

// NewFolderConnectionFields creates a new FolderConnectionFields selector
func NewFolderConnectionFields(selection *builder.FieldSelection) *FolderConnectionFields {
	return &FolderConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *FolderConnectionFields) Edges(selector func(*FolderEdgeFields)) *FolderConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewFolderEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *FolderConnectionFields) PageInfo(selector func(*PageInfoFields)) *FolderConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *FolderConnectionFields) TotalCount() *FolderConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
