// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// StudentFields provides type-safe field selection for Student
type StudentFields struct {
	selection *builder.FieldSelection
}

// NewStudentFields creates a new StudentFields selector
func NewStudentFields(selection *builder.FieldSelection) *StudentFields {
	return &StudentFields{selection: selection}
}

// Name selects the name field
func (f *StudentFields) Name() *StudentFields {
	f.selection.AddField("name")
	return f
}
