// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// GuestConnectionFields provides type-safe field selection for GuestConnection
type GuestConnectionFields struct {
	selection *builder.FieldSelection
}

// NewGuestConnectionFields creates a new GuestConnectionFields selector
func NewGuestConnectionFields(selection *builder.FieldSelection) *GuestConnectionFields {
	return &GuestConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *GuestConnectionFields) Edges(selector func(*GuestEdgeFields)) *GuestConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewGuestEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *GuestConnectionFields) PageInfo(selector func(*PageInfoFields)) *GuestConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *GuestConnectionFields) TotalCount() *GuestConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
