// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// LeadEdgeFields provides type-safe field selection for LeadEdge
type LeadEdgeFields struct {
	selection *builder.FieldSelection
}

// NewLeadEdgeFields creates a new LeadEdgeFields selector
func NewLeadEdgeFields(selection *builder.FieldSelection) *LeadEdgeFields {
	return &LeadEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *LeadEdgeFields) Node(selector func(*LeadFields)) *LeadEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewLeadFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *LeadEdgeFields) Cursor() *LeadEdgeFields {
	f.selection.AddField("cursor")
	return f
}
