// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// AiModelConnectionFields provides type-safe field selection for AiModelConnection
type AiModelConnectionFields struct {
	selection *builder.FieldSelection
}

// NewAiModelConnectionFields creates a new AiModelConnectionFields selector
func NewAiModelConnectionFields(selection *builder.FieldSelection) *AiModelConnectionFields {
	return &AiModelConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *AiModelConnectionFields) Edges(selector func(*AiModelEdgeFields)) *AiModelConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewAiModelEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *AiModelConnectionFields) PageInfo(selector func(*PageInfoFields)) *AiModelConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *AiModelConnectionFields) TotalCount() *AiModelConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
