// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ChatbotEdgeFields provides type-safe field selection for ChatbotEdge
type ChatbotEdgeFields struct {
	selection *builder.FieldSelection
}

// NewChatbotEdgeFields creates a new ChatbotEdgeFields selector
func NewChatbotEdgeFields(selection *builder.FieldSelection) *ChatbotEdgeFields {
	return &ChatbotEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ChatbotEdgeFields) Node(selector func(*ChatbotFields)) *ChatbotEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ChatbotEdgeFields) Cursor() *ChatbotEdgeFields {
	f.selection.AddField("cursor")
	return f
}
