// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// BillingPlanWspaceFields provides type-safe field selection for BillingPlanWspace
type BillingPlanWspaceFields struct {
	selection *builder.FieldSelection
}

// NewBillingPlanWspaceFields creates a new BillingPlanWspaceFields selector
func NewBillingPlanWspaceFields(selection *builder.FieldSelection) *BillingPlanWspaceFields {
	return &BillingPlanWspaceFields{selection: selection}
}

// ID selects the id field
func (f *BillingPlanWspaceFields) ID() *BillingPlanWspaceFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *BillingPlanWspaceFields) CreatedAt() *BillingPlanWspaceFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *BillingPlanWspaceFields) UpdatedAt() *BillingPlanWspaceFields {
	f.selection.AddField("updatedAt")
	return f
}

// BillingPlanID selects the billingPlanID field
func (f *BillingPlanWspaceFields) BillingPlanID() *BillingPlanWspaceFields {
	f.selection.AddField("billingPlanID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *BillingPlanWspaceFields) WorkspaceID() *BillingPlanWspaceFields {
	f.selection.AddField("workspaceID")
	return f
}

// BillingPlan selects the billingPlan field with nested selection
func (f *BillingPlanWspaceFields) BillingPlan(selector func(*BillingPlanFields)) *BillingPlanWspaceFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanFields(child))
	}
	f.selection.AddChild("billingPlan", child)
	return f
}
