// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// BillingPlanEdgeFields provides type-safe field selection for BillingPlanEdge
type BillingPlanEdgeFields struct {
	selection *builder.FieldSelection
}

// NewBillingPlanEdgeFields creates a new BillingPlanEdgeFields selector
func NewBillingPlanEdgeFields(selection *builder.FieldSelection) *BillingPlanEdgeFields {
	return &BillingPlanEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *BillingPlanEdgeFields) Node(selector func(*BillingPlanFields)) *BillingPlanEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *BillingPlanEdgeFields) Cursor() *BillingPlanEdgeFields {
	f.selection.AddField("cursor")
	return f
}
