// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// BillingPlanWspaceConnectionFields provides type-safe field selection for BillingPlanWspaceConnection
type BillingPlanWspaceConnectionFields struct {
	selection *builder.FieldSelection
}

// NewBillingPlanWspaceConnectionFields creates a new BillingPlanWspaceConnectionFields selector
func NewBillingPlanWspaceConnectionFields(selection *builder.FieldSelection) *BillingPlanWspaceConnectionFields {
	return &BillingPlanWspaceConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *BillingPlanWspaceConnectionFields) Edges(selector func(*BillingPlanWspaceEdgeFields)) *BillingPlanWspaceConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanWspaceEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *BillingPlanWspaceConnectionFields) PageInfo(selector func(*PageInfoFields)) *BillingPlanWspaceConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *BillingPlanWspaceConnectionFields) TotalCount() *BillingPlanWspaceConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
