// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// FuncToolEdgeFields provides type-safe field selection for FuncToolEdge
type FuncToolEdgeFields struct {
	selection *builder.FieldSelection
}

// NewFuncToolEdgeFields creates a new FuncToolEdgeFields selector
func NewFuncToolEdgeFields(selection *builder.FieldSelection) *FuncToolEdgeFields {
	return &FuncToolEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *FuncToolEdgeFields) Node(selector func(*FuncToolFields)) *FuncToolEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *FuncToolEdgeFields) Cursor() *FuncToolEdgeFields {
	f.selection.AddField("cursor")
	return f
}
