// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// CredentialFields provides type-safe field selection for Credential
type CredentialFields struct {
	selection *builder.FieldSelection
}

// NewCredentialFields creates a new CredentialFields selector
func NewCredentialFields(selection *builder.FieldSelection) *CredentialFields {
	return &CredentialFields{selection: selection}
}

// ID selects the id field
func (f *CredentialFields) ID() *CredentialFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *CredentialFields) CreatedAt() *CredentialFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *CredentialFields) UpdatedAt() *CredentialFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *CredentialFields) Name() *CredentialFields {
	f.selection.AddField("name")
	return f
}

// CredentialType selects the credentialType field
func (f *CredentialFields) CredentialType() *CredentialFields {
	f.selection.AddField("credentialType")
	return f
}

// Active selects the active field
func (f *CredentialFields) Active() *CredentialFields {
	f.selection.AddField("active")
	return f
}

// DbType selects the dbType field
func (f *CredentialFields) DbType() *CredentialFields {
	f.selection.AddField("dbType")
	return f
}

// DbName selects the dbName field
func (f *CredentialFields) DbName() *CredentialFields {
	f.selection.AddField("dbName")
	return f
}

// Host selects the host field
func (f *CredentialFields) Host() *CredentialFields {
	f.selection.AddField("host")
	return f
}

// Port selects the port field
func (f *CredentialFields) Port() *CredentialFields {
	f.selection.AddField("port")
	return f
}

// Username selects the username field
func (f *CredentialFields) Username() *CredentialFields {
	f.selection.AddField("username")
	return f
}

// Password selects the password field
func (f *CredentialFields) Password() *CredentialFields {
	f.selection.AddField("password")
	return f
}

// Secret selects the secret field
func (f *CredentialFields) Secret() *CredentialFields {
	f.selection.AddField("secret")
	return f
}

// APIKey selects the apiKey field
func (f *CredentialFields) APIKey() *CredentialFields {
	f.selection.AddField("apiKey")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *CredentialFields) WorkspaceID() *CredentialFields {
	f.selection.AddField("workspaceID")
	return f
}

// FuncTools selects the funcTools field with nested selection
func (f *CredentialFields) FuncTools(selector func(*FuncToolFields)) *CredentialFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolFields(child))
	}
	f.selection.AddChild("funcTools", child)
	return f
}
