// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// UserEdgeFields provides type-safe field selection for UserEdge
type UserEdgeFields struct {
	selection *builder.FieldSelection
}

// NewUserEdgeFields creates a new UserEdgeFields selector
func NewUserEdgeFields(selection *builder.FieldSelection) *UserEdgeFields {
	return &UserEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *UserEdgeFields) Node(selector func(*UserFields)) *UserEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *UserEdgeFields) Cursor() *UserEdgeFields {
	f.selection.AddField("cursor")
	return f
}
