// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// FuncToolLogEdgeFields provides type-safe field selection for FuncToolLogEdge
type FuncToolLogEdgeFields struct {
	selection *builder.FieldSelection
}

// NewFuncToolLogEdgeFields creates a new FuncToolLogEdgeFields selector
func NewFuncToolLogEdgeFields(selection *builder.FieldSelection) *FuncToolLogEdgeFields {
	return &FuncToolLogEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *FuncToolLogEdgeFields) Node(selector func(*FuncToolLogFields)) *FuncToolLogEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolLogFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *FuncToolLogEdgeFields) Cursor() *FuncToolLogEdgeFields {
	f.selection.AddField("cursor")
	return f
}
