// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// CWorkspaceFeatureLimitFields provides type-safe field selection for CWorkspaceFeatureLimit
type CWorkspaceFeatureLimitFields struct {
	selection *builder.FieldSelection
}

// NewCWorkspaceFeatureLimitFields creates a new CWorkspaceFeatureLimitFields selector
func NewCWorkspaceFeatureLimitFields(selection *builder.FieldSelection) *CWorkspaceFeatureLimitFields {
	return &CWorkspaceFeatureLimitFields{selection: selection}
}

// ID selects the id field
func (f *CWorkspaceFeatureLimitFields) ID() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *CWorkspaceFeatureLimitFields) CreatedAt() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *CWorkspaceFeatureLimitFields) UpdatedAt() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("updatedAt")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *CWorkspaceFeatureLimitFields) WorkspaceID() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("workspaceID")
	return f
}

// BillingFeatureID selects the billingFeatureID field
func (f *CWorkspaceFeatureLimitFields) BillingFeatureID() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("billingFeatureID")
	return f
}

// Available selects the available field
func (f *CWorkspaceFeatureLimitFields) Available() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("available")
	return f
}

// Used selects the used field
func (f *CWorkspaceFeatureLimitFields) Used() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("used")
	return f
}

// Balance selects the balance field
func (f *CWorkspaceFeatureLimitFields) Balance() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("balance")
	return f
}

// CalculatedAt selects the calculatedAt field
func (f *CWorkspaceFeatureLimitFields) CalculatedAt() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("calculatedAt")
	return f
}

// Sources selects the sources field
func (f *CWorkspaceFeatureLimitFields) Sources() *CWorkspaceFeatureLimitFields {
	f.selection.AddField("sources")
	return f
}

// BillingFeature selects the billingFeature field with nested selection
func (f *CWorkspaceFeatureLimitFields) BillingFeature(selector func(*BillingFeatureFields)) *CWorkspaceFeatureLimitFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingFeatureFields(child))
	}
	f.selection.AddChild("billingFeature", child)
	return f
}
