// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ItemConnectionFields provides type-safe field selection for ItemConnection
type ItemConnectionFields struct {
	selection *builder.FieldSelection
}

// NewItemConnectionFields creates a new ItemConnectionFields selector
func NewItemConnectionFields(selection *builder.FieldSelection) *ItemConnectionFields {
	return &ItemConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ItemConnectionFields) Edges(selector func(*ItemEdgeFields)) *ItemConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewItemEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ItemConnectionFields) PageInfo(selector func(*PageInfoFields)) *ItemConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ItemConnectionFields) TotalCount() *ItemConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
