// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// ItemGroupEdgeFields provides type-safe field selection for ItemGroupEdge
type ItemGroupEdgeFields struct {
	selection *builder.FieldSelection
}

// NewItemGroupEdgeFields creates a new ItemGroupEdgeFields selector
func NewItemGroupEdgeFields(selection *builder.FieldSelection) *ItemGroupEdgeFields {
	return &ItemGroupEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ItemGroupEdgeFields) Node(selector func(*ItemGroupFields)) *ItemGroupEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewItemGroupFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ItemGroupEdgeFields) Cursor() *ItemGroupEdgeFields {
	f.selection.AddField("cursor")
	return f
}
