// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// CredentialEdgeFields provides type-safe field selection for CredentialEdge
type CredentialEdgeFields struct {
	selection *builder.FieldSelection
}

// NewCredentialEdgeFields creates a new CredentialEdgeFields selector
func NewCredentialEdgeFields(selection *builder.FieldSelection) *CredentialEdgeFields {
	return &CredentialEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *CredentialEdgeFields) Node(selector func(*CredentialFields)) *CredentialEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewCredentialFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *CredentialEdgeFields) Cursor() *CredentialEdgeFields {
	f.selection.AddField("cursor")
	return f
}
