// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// AppStorePartnerFields provides type-safe field selection for AppStorePartner
type AppStorePartnerFields struct {
	selection *builder.FieldSelection
}

// NewAppStorePartnerFields creates a new AppStorePartnerFields selector
func NewAppStorePartnerFields(selection *builder.FieldSelection) *AppStorePartnerFields {
	return &AppStorePartnerFields{selection: selection}
}

// ID selects the id field
func (f *AppStorePartnerFields) ID() *AppStorePartnerFields {
	f.selection.AddField("id")
	return f
}

// Name selects the name field
func (f *AppStorePartnerFields) Name() *AppStorePartnerFields {
	f.selection.AddField("name")
	return f
}

// CompanyName selects the companyName field
func (f *AppStorePartnerFields) CompanyName() *AppStorePartnerFields {
	f.selection.AddField("companyName")
	return f
}
