// Code generated by gqlkit. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// BillingPlanConnectionFields provides type-safe field selection for BillingPlanConnection
type BillingPlanConnectionFields struct {
	selection *builder.FieldSelection
}

// NewBillingPlanConnectionFields creates a new BillingPlanConnectionFields selector
func NewBillingPlanConnectionFields(selection *builder.FieldSelection) *BillingPlanConnectionFields {
	return &BillingPlanConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *BillingPlanConnectionFields) Edges(selector func(*BillingPlanEdgeFields)) *BillingPlanConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *BillingPlanConnectionFields) PageInfo(selector func(*PageInfoFields)) *BillingPlanConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *BillingPlanConnectionFields) TotalCount() *BillingPlanConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
