// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"example-go-chat/sdk/builder"
)

// BillingPlanFeatureFields provides type-safe field selection for BillingPlanFeature
type BillingPlanFeatureFields struct {
	selection *builder.FieldSelection
}

// NewBillingPlanFeatureFields creates a new BillingPlanFeatureFields selector
func NewBillingPlanFeatureFields(selection *builder.FieldSelection) *BillingPlanFeatureFields {
	return &BillingPlanFeatureFields{selection: selection}
}

// ID selects the id field
func (f *BillingPlanFeatureFields) ID() *BillingPlanFeatureFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *BillingPlanFeatureFields) CreatedAt() *BillingPlanFeatureFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *BillingPlanFeatureFields) UpdatedAt() *BillingPlanFeatureFields {
	f.selection.AddField("updatedAt")
	return f
}

// FeatureID selects the featureID field
func (f *BillingPlanFeatureFields) FeatureID() *BillingPlanFeatureFields {
	f.selection.AddField("featureID")
	return f
}

// Value selects the value field
func (f *BillingPlanFeatureFields) Value() *BillingPlanFeatureFields {
	f.selection.AddField("value")
	return f
}

// BillingPlanID selects the billingPlanID field
func (f *BillingPlanFeatureFields) BillingPlanID() *BillingPlanFeatureFields {
	f.selection.AddField("billingPlanID")
	return f
}

// BillingPlan selects the billingPlan field with nested selection
func (f *BillingPlanFeatureFields) BillingPlan(selector func(*BillingPlanFields)) *BillingPlanFeatureFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanFields(child))
	}
	f.selection.AddChild("billingPlan", child)
	return f
}

// BillingFeature selects the billingFeature field with nested selection
func (f *BillingPlanFeatureFields) BillingFeature(selector func(*BillingFeatureFields)) *BillingPlanFeatureFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingFeatureFields(child))
	}
	f.selection.AddChild("billingFeature", child)
	return f
}
