// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
)

// ICanUserAccessChatbotBuilder builds a query for iCanUserAccessChatbot
type ICanUserAccessChatbotBuilder struct {
	*builder.BaseBuilder
}

// ID sets the id argument
func (b *ICanUserAccessChatbotBuilder) ID(v string) *ICanUserAccessChatbotBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// AiUserID sets the aiUserID argument
func (b *ICanUserAccessChatbotBuilder) AiUserID(v string) *ICanUserAccessChatbotBuilder {
	b.SetArg("aiUserID", v, "String!")
	return b
}

// Execute runs the query and returns the result
func (b *ICanUserAccessChatbotBuilder) Execute(ctx context.Context) (bool, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result bool `json:"iCanUserAccessChatbot"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return false, err
	}

	return response.Result, nil
}
