// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
)

// IsAppInstalledBuilder builds a query for isAppInstalled
type IsAppInstalledBuilder struct {
	*builder.BaseBuilder
}

// AppID sets the appId argument
func (b *IsAppInstalledBuilder) AppID(v string) *IsAppInstalledBuilder {
	b.SetArg("appId", v, "ID!")
	return b
}

// Execute runs the query and returns the result
func (b *IsAppInstalledBuilder) Execute(ctx context.Context) (bool, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result bool `json:"isAppInstalled"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return false, err
	}

	return response.Result, nil
}
