// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/types"
)

// InstalledAppsBuilder builds a query for installedApps
type InstalledAppsBuilder struct {
	*builder.BaseBuilder
}

// Select configures which fields to return
func (b *InstalledAppsBuilder) Select(selector func(*fields.WorkspaceAppInstallationFields)) *InstalledAppsBuilder {
	selector(fields.NewWorkspaceAppInstallationFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *InstalledAppsBuilder) Execute(ctx context.Context) ([]types.WorkspaceAppInstallation, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []types.WorkspaceAppInstallation `json:"installedApps"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
