// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/types"
)

// WorkspaceSubscriptionsBuilder builds a query for workspaceSubscriptions
type WorkspaceSubscriptionsBuilder struct {
	*builder.BaseBuilder
}

// Select configures which fields to return
func (b *WorkspaceSubscriptionsBuilder) Select(selector func(*fields.CWorkspaceSubFields)) *WorkspaceSubscriptionsBuilder {
	selector(fields.NewCWorkspaceSubFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *WorkspaceSubscriptionsBuilder) Execute(ctx context.Context) ([]*types.CWorkspaceSub, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []*types.CWorkspaceSub `json:"workspaceSubscriptions"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
