// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/types"
)

// ItemGroupBuilder builds a query for itemGroup
type ItemGroupBuilder struct {
	*builder.BaseBuilder
}

// ID sets the id argument
func (b *ItemGroupBuilder) ID(v string) *ItemGroupBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// Select configures which fields to return
func (b *ItemGroupBuilder) Select(selector func(*fields.ItemGroupFields)) *ItemGroupBuilder {
	selector(fields.NewItemGroupFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ItemGroupBuilder) Execute(ctx context.Context) (types.ItemGroup, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.ItemGroup `json:"itemGroup"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.ItemGroup{}, err
	}

	return response.Result, nil
}
