// Code generated by gqlcustom. DO NOT EDIT.

package queries

import "example-go-chat/sdk/builder"

// QueryRoot is the entry point for queries
type QueryRoot struct {
	client builder.GraphQLClient
}

// NewQueryRoot creates a new QueryRoot
func NewQueryRoot(client builder.GraphQLClient) *QueryRoot {
	return &QueryRoot{client: client}
}

// Node creates a new NodeBuilder
func (q *QueryRoot) Node() *NodeBuilder {
	return &NodeBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Node", "node"),
	}
}

// Nodes creates a new NodesBuilder
func (q *QueryRoot) Nodes() *NodesBuilder {
	return &NodesBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Nodes", "nodes"),
	}
}

// AiModels creates a new AiModelsBuilder
func (q *QueryRoot) AiModels() *AiModelsBuilder {
	return &AiModelsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "AiModels", "aiModels"),
	}
}

// AiModels2 creates a new AiModels2Builder
func (q *QueryRoot) AiModels2() *AiModels2Builder {
	return &AiModels2Builder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "AiModels2", "aiModels2"),
	}
}

// BillingFeatures creates a new BillingFeaturesBuilder
func (q *QueryRoot) BillingFeatures() *BillingFeaturesBuilder {
	return &BillingFeaturesBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "BillingFeatures", "billingFeatures"),
	}
}

// BillingPlans creates a new BillingPlansBuilder
func (q *QueryRoot) BillingPlans() *BillingPlansBuilder {
	return &BillingPlansBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "BillingPlans", "billingPlans"),
	}
}

// BillingPlanWspaces creates a new BillingPlanWspacesBuilder
func (q *QueryRoot) BillingPlanWspaces() *BillingPlanWspacesBuilder {
	return &BillingPlanWspacesBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "BillingPlanWspaces", "billingPlanWspaces"),
	}
}

// CworkspaceFeatureLimits creates a new CworkspaceFeatureLimitsBuilder
func (q *QueryRoot) CworkspaceFeatureLimits() *CworkspaceFeatureLimitsBuilder {
	return &CworkspaceFeatureLimitsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "CworkspaceFeatureLimits", "cworkspaceFeatureLimits"),
	}
}

// CworkspaceSubs creates a new CworkspaceSubsBuilder
func (q *QueryRoot) CworkspaceSubs() *CworkspaceSubsBuilder {
	return &CworkspaceSubsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "CworkspaceSubs", "cworkspaceSubs"),
	}
}

// Channels creates a new ChannelsBuilder
func (q *QueryRoot) Channels() *ChannelsBuilder {
	return &ChannelsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Channels", "channels"),
	}
}

// ChannelUsers creates a new ChannelUsersBuilder
func (q *QueryRoot) ChannelUsers() *ChannelUsersBuilder {
	return &ChannelUsersBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "ChannelUsers", "channelUsers"),
	}
}

// Chatbots creates a new ChatbotsBuilder
func (q *QueryRoot) Chatbots() *ChatbotsBuilder {
	return &ChatbotsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Chatbots", "chatbots"),
	}
}

// ChatbotTools creates a new ChatbotToolsBuilder
func (q *QueryRoot) ChatbotTools() *ChatbotToolsBuilder {
	return &ChatbotToolsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "ChatbotTools", "chatbotTools"),
	}
}

// ChatbotUsers creates a new ChatbotUsersBuilder
func (q *QueryRoot) ChatbotUsers() *ChatbotUsersBuilder {
	return &ChatbotUsersBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "ChatbotUsers", "chatbotUsers"),
	}
}

// Credentials creates a new CredentialsBuilder
func (q *QueryRoot) Credentials() *CredentialsBuilder {
	return &CredentialsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Credentials", "credentials"),
	}
}

// Folders creates a new FoldersBuilder
func (q *QueryRoot) Folders() *FoldersBuilder {
	return &FoldersBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Folders", "folders"),
	}
}

// FuncTools creates a new FuncToolsBuilder
func (q *QueryRoot) FuncTools() *FuncToolsBuilder {
	return &FuncToolsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "FuncTools", "funcTools"),
	}
}

// FuncToolLogs creates a new FuncToolLogsBuilder
func (q *QueryRoot) FuncToolLogs() *FuncToolLogsBuilder {
	return &FuncToolLogsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "FuncToolLogs", "funcToolLogs"),
	}
}

// Guests creates a new GuestsBuilder
func (q *QueryRoot) Guests() *GuestsBuilder {
	return &GuestsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Guests", "guests"),
	}
}

// Items creates a new ItemsBuilder
func (q *QueryRoot) Items() *ItemsBuilder {
	return &ItemsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Items", "items"),
	}
}

// ItemGroups creates a new ItemGroupsBuilder
func (q *QueryRoot) ItemGroups() *ItemGroupsBuilder {
	return &ItemGroupsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "ItemGroups", "itemGroups"),
	}
}

// ItemGroupSources creates a new ItemGroupSourcesBuilder
func (q *QueryRoot) ItemGroupSources() *ItemGroupSourcesBuilder {
	return &ItemGroupSourcesBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "ItemGroupSources", "itemGroupSources"),
	}
}

// Leads creates a new LeadsBuilder
func (q *QueryRoot) Leads() *LeadsBuilder {
	return &LeadsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Leads", "leads"),
	}
}

// Messages creates a new MessagesBuilder
func (q *QueryRoot) Messages() *MessagesBuilder {
	return &MessagesBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Messages", "messages"),
	}
}

// Users creates a new UsersBuilder
func (q *QueryRoot) Users() *UsersBuilder {
	return &UsersBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Users", "users"),
	}
}

// AvailableApps creates a new AvailableAppsBuilder
func (q *QueryRoot) AvailableApps() *AvailableAppsBuilder {
	return &AvailableAppsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "AvailableApps", "availableApps"),
	}
}

// InstalledApps creates a new InstalledAppsBuilder
func (q *QueryRoot) InstalledApps() *InstalledAppsBuilder {
	return &InstalledAppsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "InstalledApps", "installedApps"),
	}
}

// IsAppInstalled creates a new IsAppInstalledBuilder
func (q *QueryRoot) IsAppInstalled() *IsAppInstalledBuilder {
	return &IsAppInstalledBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "IsAppInstalled", "isAppInstalled"),
	}
}

// WorkspaceSubscriptions creates a new WorkspaceSubscriptionsBuilder
func (q *QueryRoot) WorkspaceSubscriptions() *WorkspaceSubscriptionsBuilder {
	return &WorkspaceSubscriptionsBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "WorkspaceSubscriptions", "workspaceSubscriptions"),
	}
}

// BillingCustomPlans creates a new BillingCustomPlansBuilder
func (q *QueryRoot) BillingCustomPlans() *BillingCustomPlansBuilder {
	return &BillingCustomPlansBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "BillingCustomPlans", "billingCustomPlans"),
	}
}

// Chatbot creates a new ChatbotBuilder
func (q *QueryRoot) Chatbot() *ChatbotBuilder {
	return &ChatbotBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Chatbot", "chatbot"),
	}
}

// MyChatbotUsers creates a new MyChatbotUsersBuilder
func (q *QueryRoot) MyChatbotUsers() *MyChatbotUsersBuilder {
	return &MyChatbotUsersBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "MyChatbotUsers", "myChatbotUsers"),
	}
}

// ChatbotFolders creates a new ChatbotFoldersBuilder
func (q *QueryRoot) ChatbotFolders() *ChatbotFoldersBuilder {
	return &ChatbotFoldersBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "ChatbotFolders", "chatbotFolders"),
	}
}

// IChatbot creates a new IChatbotBuilder
func (q *QueryRoot) IChatbot() *IChatbotBuilder {
	return &IChatbotBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "IChatbot", "iChatbot"),
	}
}

// IChannel creates a new IChannelBuilder
func (q *QueryRoot) IChannel() *IChannelBuilder {
	return &IChannelBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "IChannel", "iChannel"),
	}
}

// ICanUserAccessChatbot creates a new ICanUserAccessChatbotBuilder
func (q *QueryRoot) ICanUserAccessChatbot() *ICanUserAccessChatbotBuilder {
	return &ICanUserAccessChatbotBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "ICanUserAccessChatbot", "iCanUserAccessChatbot"),
	}
}

// ICanUserAccessChannel creates a new ICanUserAccessChannelBuilder
func (q *QueryRoot) ICanUserAccessChannel() *ICanUserAccessChannelBuilder {
	return &ICanUserAccessChannelBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "ICanUserAccessChannel", "iCanUserAccessChannel"),
	}
}

// ICanUserAccessWorkspace creates a new ICanUserAccessWorkspaceBuilder
func (q *QueryRoot) ICanUserAccessWorkspace() *ICanUserAccessWorkspaceBuilder {
	return &ICanUserAccessWorkspaceBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "ICanUserAccessWorkspace", "iCanUserAccessWorkspace"),
	}
}

// IAiModel creates a new IAiModelBuilder
func (q *QueryRoot) IAiModel() *IAiModelBuilder {
	return &IAiModelBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "IAiModel", "iAiModel"),
	}
}

// ItemAiSearch creates a new ItemAiSearchBuilder
func (q *QueryRoot) ItemAiSearch() *ItemAiSearchBuilder {
	return &ItemAiSearchBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "ItemAiSearch", "itemAiSearch"),
	}
}

// ItemGroup creates a new ItemGroupBuilder
func (q *QueryRoot) ItemGroup() *ItemGroupBuilder {
	return &ItemGroupBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "ItemGroup", "itemGroup"),
	}
}

// ItemGroupSourcesSummary creates a new ItemGroupSourcesSummaryBuilder
func (q *QueryRoot) ItemGroupSourcesSummary() *ItemGroupSourcesSummaryBuilder {
	return &ItemGroupSourcesSummaryBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "ItemGroupSourcesSummary", "itemGroupSourcesSummary"),
	}
}

// WorkspaceDetail creates a new WorkspaceDetailBuilder
func (q *QueryRoot) WorkspaceDetail() *WorkspaceDetailBuilder {
	return &WorkspaceDetailBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "WorkspaceDetail", "workspaceDetail"),
	}
}

// Ping creates a new PingBuilder
func (q *QueryRoot) Ping() *PingBuilder {
	return &PingBuilder{
		BaseBuilder: builder.NewBaseBuilder(q.client, "query", "Ping", "ping"),
	}
}
