// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// MessageConnectionFields provides type-safe field selection for MessageConnection
type MessageConnectionFields struct {
	selection *builder.FieldSelection
}

// NewMessageConnectionFields creates a new MessageConnectionFields selector
func NewMessageConnectionFields(selection *builder.FieldSelection) *MessageConnectionFields {
	return &MessageConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *MessageConnectionFields) Edges(selector func(*MessageEdgeFields)) *MessageConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewMessageEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *MessageConnectionFields) PageInfo(selector func(*PageInfoFields)) *MessageConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *MessageConnectionFields) TotalCount() *MessageConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
