// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// CreateChatbotResponseFields provides type-safe field selection for CreateChatbotResponse
type CreateChatbotResponseFields struct {
	selection *builder.FieldSelection
}

// NewCreateChatbotResponseFields creates a new CreateChatbotResponseFields selector
func NewCreateChatbotResponseFields(selection *builder.FieldSelection) *CreateChatbotResponseFields {
	return &CreateChatbotResponseFields{selection: selection}
}

// Chatbot selects the chatbot field with nested selection
func (f *CreateChatbotResponseFields) Chatbot(selector func(*ChatbotFields)) *CreateChatbotResponseFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbot", child)
	return f
}

// ItemGroup selects the itemGroup field with nested selection
func (f *CreateChatbotResponseFields) ItemGroup(selector func(*ItemGroupFields)) *CreateChatbotResponseFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewItemGroupFields(child))
	}
	f.selection.AddChild("itemGroup", child)
	return f
}
