// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// CWorkspaceSubFields provides type-safe field selection for CWorkspaceSub
type CWorkspaceSubFields struct {
	selection *builder.FieldSelection
}

// NewCWorkspaceSubFields creates a new CWorkspaceSubFields selector
func NewCWorkspaceSubFields(selection *builder.FieldSelection) *CWorkspaceSubFields {
	return &CWorkspaceSubFields{selection: selection}
}

// ID selects the id field
func (f *CWorkspaceSubFields) ID() *CWorkspaceSubFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *CWorkspaceSubFields) CreatedAt() *CWorkspaceSubFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *CWorkspaceSubFields) UpdatedAt() *CWorkspaceSubFields {
	f.selection.AddField("updatedAt")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *CWorkspaceSubFields) WorkspaceID() *CWorkspaceSubFields {
	f.selection.AddField("workspaceID")
	return f
}

// Lock selects the lock field
func (f *CWorkspaceSubFields) Lock() *CWorkspaceSubFields {
	f.selection.AddField("lock")
	return f
}

// BillingPlanID selects the billingPlanID field
func (f *CWorkspaceSubFields) BillingPlanID() *CWorkspaceSubFields {
	f.selection.AddField("billingPlanID")
	return f
}

// Status selects the status field
func (f *CWorkspaceSubFields) Status() *CWorkspaceSubFields {
	f.selection.AddField("status")
	return f
}

// StripeStatus selects the stripeStatus field
func (f *CWorkspaceSubFields) StripeStatus() *CWorkspaceSubFields {
	f.selection.AddField("stripeStatus")
	return f
}

// IsSubscription selects the isSubscription field
func (f *CWorkspaceSubFields) IsSubscription() *CWorkspaceSubFields {
	f.selection.AddField("isSubscription")
	return f
}

// CheckoutSessionID selects the checkoutSessionID field
func (f *CWorkspaceSubFields) CheckoutSessionID() *CWorkspaceSubFields {
	f.selection.AddField("checkoutSessionID")
	return f
}

// Amount selects the amount field
func (f *CWorkspaceSubFields) Amount() *CWorkspaceSubFields {
	f.selection.AddField("amount")
	return f
}

// Qty selects the qty field
func (f *CWorkspaceSubFields) Qty() *CWorkspaceSubFields {
	f.selection.AddField("qty")
	return f
}

// SubscriptionID selects the subscriptionID field
func (f *CWorkspaceSubFields) SubscriptionID() *CWorkspaceSubFields {
	f.selection.AddField("subscriptionID")
	return f
}

// SubscriptionItemID selects the subscriptionItemID field
func (f *CWorkspaceSubFields) SubscriptionItemID() *CWorkspaceSubFields {
	f.selection.AddField("subscriptionItemID")
	return f
}

// PlanInterval selects the planInterval field
func (f *CWorkspaceSubFields) PlanInterval() *CWorkspaceSubFields {
	f.selection.AddField("planInterval")
	return f
}

// PlanIntervalCount selects the planIntervalCount field
func (f *CWorkspaceSubFields) PlanIntervalCount() *CWorkspaceSubFields {
	f.selection.AddField("planIntervalCount")
	return f
}

// ItemID selects the itemID field
func (f *CWorkspaceSubFields) ItemID() *CWorkspaceSubFields {
	f.selection.AddField("itemID")
	return f
}

// ItemPriceID selects the itemPriceID field
func (f *CWorkspaceSubFields) ItemPriceID() *CWorkspaceSubFields {
	f.selection.AddField("itemPriceID")
	return f
}

// ItemName selects the itemName field
func (f *CWorkspaceSubFields) ItemName() *CWorkspaceSubFields {
	f.selection.AddField("itemName")
	return f
}

// InvoiceID selects the invoiceID field
func (f *CWorkspaceSubFields) InvoiceID() *CWorkspaceSubFields {
	f.selection.AddField("invoiceID")
	return f
}

// InvoiceLineID selects the invoiceLineID field
func (f *CWorkspaceSubFields) InvoiceLineID() *CWorkspaceSubFields {
	f.selection.AddField("invoiceLineID")
	return f
}

// InvoiceNumber selects the invoiceNumber field
func (f *CWorkspaceSubFields) InvoiceNumber() *CWorkspaceSubFields {
	f.selection.AddField("invoiceNumber")
	return f
}

// CurrentPeriodStart selects the currentPeriodStart field
func (f *CWorkspaceSubFields) CurrentPeriodStart() *CWorkspaceSubFields {
	f.selection.AddField("currentPeriodStart")
	return f
}

// CurrentPeriodEnd selects the currentPeriodEnd field
func (f *CWorkspaceSubFields) CurrentPeriodEnd() *CWorkspaceSubFields {
	f.selection.AddField("currentPeriodEnd")
	return f
}

// CancelAt selects the cancelAt field
func (f *CWorkspaceSubFields) CancelAt() *CWorkspaceSubFields {
	f.selection.AddField("cancelAt")
	return f
}

// CancelAtPeriodEnd selects the cancelAtPeriodEnd field
func (f *CWorkspaceSubFields) CancelAtPeriodEnd() *CWorkspaceSubFields {
	f.selection.AddField("cancelAtPeriodEnd")
	return f
}

// CanceledAt selects the canceledAt field
func (f *CWorkspaceSubFields) CanceledAt() *CWorkspaceSubFields {
	f.selection.AddField("canceledAt")
	return f
}

// StripeCustomerID selects the stripeCustomerID field
func (f *CWorkspaceSubFields) StripeCustomerID() *CWorkspaceSubFields {
	f.selection.AddField("stripeCustomerID")
	return f
}

// StripeCustomerEmail selects the stripeCustomerEmail field
func (f *CWorkspaceSubFields) StripeCustomerEmail() *CWorkspaceSubFields {
	f.selection.AddField("stripeCustomerEmail")
	return f
}

// LastCheckedAt selects the lastCheckedAt field
func (f *CWorkspaceSubFields) LastCheckedAt() *CWorkspaceSubFields {
	f.selection.AddField("lastCheckedAt")
	return f
}

// BillingPlan selects the billingPlan field with nested selection
func (f *CWorkspaceSubFields) BillingPlan(selector func(*BillingPlanFields)) *CWorkspaceSubFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanFields(child))
	}
	f.selection.AddChild("billingPlan", child)
	return f
}
