// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// HtmlToMarkdownResponseFields provides type-safe field selection for HtmlToMarkdownResponse
type HtmlToMarkdownResponseFields struct {
	selection *builder.FieldSelection
}

// NewHtmlToMarkdownResponseFields creates a new HtmlToMarkdownResponseFields selector
func NewHtmlToMarkdownResponseFields(selection *builder.FieldSelection) *HtmlToMarkdownResponseFields {
	return &HtmlToMarkdownResponseFields{selection: selection}
}

// Content selects the content field
func (f *HtmlToMarkdownResponseFields) Content() *HtmlToMarkdownResponseFields {
	f.selection.AddField("content")
	return f
}
