// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// ChatbotUserConnectionFields provides type-safe field selection for ChatbotUserConnection
type ChatbotUserConnectionFields struct {
	selection *builder.FieldSelection
}

// NewChatbotUserConnectionFields creates a new ChatbotUserConnectionFields selector
func NewChatbotUserConnectionFields(selection *builder.FieldSelection) *ChatbotUserConnectionFields {
	return &ChatbotUserConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *ChatbotUserConnectionFields) Edges(selector func(*ChatbotUserEdgeFields)) *ChatbotUserConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotUserEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *ChatbotUserConnectionFields) PageInfo(selector func(*PageInfoFields)) *ChatbotUserConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *ChatbotUserConnectionFields) TotalCount() *ChatbotUserConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
