// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// BillingFeatureConnectionFields provides type-safe field selection for BillingFeatureConnection
type BillingFeatureConnectionFields struct {
	selection *builder.FieldSelection
}

// NewBillingFeatureConnectionFields creates a new BillingFeatureConnectionFields selector
func NewBillingFeatureConnectionFields(selection *builder.FieldSelection) *BillingFeatureConnectionFields {
	return &BillingFeatureConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *BillingFeatureConnectionFields) Edges(selector func(*BillingFeatureEdgeFields)) *BillingFeatureConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingFeatureEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *BillingFeatureConnectionFields) PageInfo(selector func(*PageInfoFields)) *BillingFeatureConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *BillingFeatureConnectionFields) TotalCount() *BillingFeatureConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
