// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// ItemGroupFields provides type-safe field selection for ItemGroup
type ItemGroupFields struct {
	selection *builder.FieldSelection
}

// NewItemGroupFields creates a new ItemGroupFields selector
func NewItemGroupFields(selection *builder.FieldSelection) *ItemGroupFields {
	return &ItemGroupFields{selection: selection}
}

// ID selects the id field
func (f *ItemGroupFields) ID() *ItemGroupFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *ItemGroupFields) CreatedAt() *ItemGroupFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *ItemGroupFields) UpdatedAt() *ItemGroupFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *ItemGroupFields) Name() *ItemGroupFields {
	f.selection.AddField("name")
	return f
}

// ShortDescr selects the shortDescr field
func (f *ItemGroupFields) ShortDescr() *ItemGroupFields {
	f.selection.AddField("shortDescr")
	return f
}

// AiModelID selects the aiModelID field
func (f *ItemGroupFields) AiModelID() *ItemGroupFields {
	f.selection.AddField("aiModelID")
	return f
}

// Dims selects the dims field
func (f *ItemGroupFields) Dims() *ItemGroupFields {
	f.selection.AddField("dims")
	return f
}

// HasPendingItems selects the hasPendingItems field
func (f *ItemGroupFields) HasPendingItems() *ItemGroupFields {
	f.selection.AddField("hasPendingItems")
	return f
}

// Locked selects the locked field
func (f *ItemGroupFields) Locked() *ItemGroupFields {
	f.selection.AddField("locked")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *ItemGroupFields) WorkspaceID() *ItemGroupFields {
	f.selection.AddField("workspaceID")
	return f
}

// ItemGroupSources selects the itemGroupSources field with nested selection
func (f *ItemGroupFields) ItemGroupSources(selector func(*ItemGroupSourceConnectionFields)) *ItemGroupFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewItemGroupSourceConnectionFields(child))
	}
	f.selection.AddChild("itemGroupSources", child)
	return f
}

// FuncTools selects the funcTools field with nested selection
func (f *ItemGroupFields) FuncTools(selector func(*FuncToolFields)) *ItemGroupFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolFields(child))
	}
	f.selection.AddChild("funcTools", child)
	return f
}

// AiModel selects the aiModel field with nested selection
func (f *ItemGroupFields) AiModel(selector func(*AiModelFields)) *ItemGroupFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewAiModelFields(child))
	}
	f.selection.AddChild("aiModel", child)
	return f
}
