// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// ChatbotUserFields provides type-safe field selection for ChatbotUser
type ChatbotUserFields struct {
	selection *builder.FieldSelection
}

// NewChatbotUserFields creates a new ChatbotUserFields selector
func NewChatbotUserFields(selection *builder.FieldSelection) *ChatbotUserFields {
	return &ChatbotUserFields{selection: selection}
}

// ID selects the id field
func (f *ChatbotUserFields) ID() *ChatbotUserFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *ChatbotUserFields) CreatedAt() *ChatbotUserFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *ChatbotUserFields) UpdatedAt() *ChatbotUserFields {
	f.selection.AddField("updatedAt")
	return f
}

// UserID selects the userID field
func (f *ChatbotUserFields) UserID() *ChatbotUserFields {
	f.selection.AddField("userID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *ChatbotUserFields) ChatbotID() *ChatbotUserFields {
	f.selection.AddField("chatbotID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *ChatbotUserFields) WorkspaceID() *ChatbotUserFields {
	f.selection.AddField("workspaceID")
	return f
}

// User selects the user field with nested selection
func (f *ChatbotUserFields) User(selector func(*UserFields)) *ChatbotUserFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("user", child)
	return f
}

// Chatbot selects the chatbot field with nested selection
func (f *ChatbotUserFields) Chatbot(selector func(*ChatbotFields)) *ChatbotUserFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbot", child)
	return f
}
