// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// GuestEdgeFields provides type-safe field selection for GuestEdge
type GuestEdgeFields struct {
	selection *builder.FieldSelection
}

// NewGuestEdgeFields creates a new GuestEdgeFields selector
func NewGuestEdgeFields(selection *builder.FieldSelection) *GuestEdgeFields {
	return &GuestEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *GuestEdgeFields) Node(selector func(*GuestFields)) *GuestEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewGuestFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *GuestEdgeFields) Cursor() *GuestEdgeFields {
	f.selection.AddField("cursor")
	return f
}
