// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// MessageEdgeFields provides type-safe field selection for MessageEdge
type MessageEdgeFields struct {
	selection *builder.FieldSelection
}

// NewMessageEdgeFields creates a new MessageEdgeFields selector
func NewMessageEdgeFields(selection *builder.FieldSelection) *MessageEdgeFields {
	return &MessageEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *MessageEdgeFields) Node(selector func(*MessageFields)) *MessageEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewMessageFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *MessageEdgeFields) Cursor() *MessageEdgeFields {
	f.selection.AddField("cursor")
	return f
}
