// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// UserConnectionFields provides type-safe field selection for UserConnection
type UserConnectionFields struct {
	selection *builder.FieldSelection
}

// NewUserConnectionFields creates a new UserConnectionFields selector
func NewUserConnectionFields(selection *builder.FieldSelection) *UserConnectionFields {
	return &UserConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *UserConnectionFields) Edges(selector func(*UserEdgeFields)) *UserConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewUserEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *UserConnectionFields) PageInfo(selector func(*PageInfoFields)) *UserConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *UserConnectionFields) TotalCount() *UserConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
