// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// CredentialConnectionFields provides type-safe field selection for CredentialConnection
type CredentialConnectionFields struct {
	selection *builder.FieldSelection
}

// NewCredentialConnectionFields creates a new CredentialConnectionFields selector
func NewCredentialConnectionFields(selection *builder.FieldSelection) *CredentialConnectionFields {
	return &CredentialConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *CredentialConnectionFields) Edges(selector func(*CredentialEdgeFields)) *CredentialConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewCredentialEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *CredentialConnectionFields) PageInfo(selector func(*PageInfoFields)) *CredentialConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *CredentialConnectionFields) TotalCount() *CredentialConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
