// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// FuncToolLogFields provides type-safe field selection for FuncToolLog
type FuncToolLogFields struct {
	selection *builder.FieldSelection
}

// NewFuncToolLogFields creates a new FuncToolLogFields selector
func NewFuncToolLogFields(selection *builder.FieldSelection) *FuncToolLogFields {
	return &FuncToolLogFields{selection: selection}
}

// ID selects the id field
func (f *FuncToolLogFields) ID() *FuncToolLogFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *FuncToolLogFields) CreatedAt() *FuncToolLogFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *FuncToolLogFields) UpdatedAt() *FuncToolLogFields {
	f.selection.AddField("updatedAt")
	return f
}

// ToolCallID selects the toolCallID field
func (f *FuncToolLogFields) ToolCallID() *FuncToolLogFields {
	f.selection.AddField("toolCallID")
	return f
}

// LogType selects the logType field
func (f *FuncToolLogFields) LogType() *FuncToolLogFields {
	f.selection.AddField("logType")
	return f
}

// Msg selects the msg field
func (f *FuncToolLogFields) Msg() *FuncToolLogFields {
	f.selection.AddField("msg")
	return f
}

// Body selects the body field
func (f *FuncToolLogFields) Body() *FuncToolLogFields {
	f.selection.AddField("body")
	return f
}

// FuncToolID selects the funcToolID field
func (f *FuncToolLogFields) FuncToolID() *FuncToolLogFields {
	f.selection.AddField("funcToolID")
	return f
}

// ChannelID selects the channelID field
func (f *FuncToolLogFields) ChannelID() *FuncToolLogFields {
	f.selection.AddField("channelID")
	return f
}

// UserID selects the userID field
func (f *FuncToolLogFields) UserID() *FuncToolLogFields {
	f.selection.AddField("userID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *FuncToolLogFields) WorkspaceID() *FuncToolLogFields {
	f.selection.AddField("workspaceID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *FuncToolLogFields) ChatbotID() *FuncToolLogFields {
	f.selection.AddField("chatbotID")
	return f
}

// FuncTool selects the funcTool field with nested selection
func (f *FuncToolLogFields) FuncTool(selector func(*FuncToolFields)) *FuncToolLogFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolFields(child))
	}
	f.selection.AddChild("funcTool", child)
	return f
}
