// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// ChatbotToolFields provides type-safe field selection for ChatbotTool
type ChatbotToolFields struct {
	selection *builder.FieldSelection
}

// NewChatbotToolFields creates a new ChatbotToolFields selector
func NewChatbotToolFields(selection *builder.FieldSelection) *ChatbotToolFields {
	return &ChatbotToolFields{selection: selection}
}

// ID selects the id field
func (f *ChatbotToolFields) ID() *ChatbotToolFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *ChatbotToolFields) CreatedAt() *ChatbotToolFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *ChatbotToolFields) UpdatedAt() *ChatbotToolFields {
	f.selection.AddField("updatedAt")
	return f
}

// FuncToolID selects the funcToolID field
func (f *ChatbotToolFields) FuncToolID() *ChatbotToolFields {
	f.selection.AddField("funcToolID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *ChatbotToolFields) ChatbotID() *ChatbotToolFields {
	f.selection.AddField("chatbotID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *ChatbotToolFields) WorkspaceID() *ChatbotToolFields {
	f.selection.AddField("workspaceID")
	return f
}

// FuncTool selects the funcTool field with nested selection
func (f *ChatbotToolFields) FuncTool(selector func(*FuncToolFields)) *ChatbotToolFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewFuncToolFields(child))
	}
	f.selection.AddChild("funcTool", child)
	return f
}

// Chatbot selects the chatbot field with nested selection
func (f *ChatbotToolFields) Chatbot(selector func(*ChatbotFields)) *ChatbotToolFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotFields(child))
	}
	f.selection.AddChild("chatbot", child)
	return f
}
