// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// AiModelEdgeFields provides type-safe field selection for AiModelEdge
type AiModelEdgeFields struct {
	selection *builder.FieldSelection
}

// NewAiModelEdgeFields creates a new AiModelEdgeFields selector
func NewAiModelEdgeFields(selection *builder.FieldSelection) *AiModelEdgeFields {
	return &AiModelEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *AiModelEdgeFields) Node(selector func(*AiModelFields)) *AiModelEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewAiModelFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *AiModelEdgeFields) Cursor() *AiModelEdgeFields {
	f.selection.AddField("cursor")
	return f
}
