// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// BillingFeatureFields provides type-safe field selection for BillingFeature
type BillingFeatureFields struct {
	selection *builder.FieldSelection
}

// NewBillingFeatureFields creates a new BillingFeatureFields selector
func NewBillingFeatureFields(selection *builder.FieldSelection) *BillingFeatureFields {
	return &BillingFeatureFields{selection: selection}
}

// ID selects the id field
func (f *BillingFeatureFields) ID() *BillingFeatureFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *BillingFeatureFields) CreatedAt() *BillingFeatureFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *BillingFeatureFields) UpdatedAt() *BillingFeatureFields {
	f.selection.AddField("updatedAt")
	return f
}

// Name selects the name field
func (f *BillingFeatureFields) Name() *BillingFeatureFields {
	f.selection.AddField("name")
	return f
}

// GroupName selects the groupName field
func (f *BillingFeatureFields) GroupName() *BillingFeatureFields {
	f.selection.AddField("groupName")
	return f
}

// IsActive selects the isActive field
func (f *BillingFeatureFields) IsActive() *BillingFeatureFields {
	f.selection.AddField("isActive")
	return f
}

// DefaultValue selects the defaultValue field
func (f *BillingFeatureFields) DefaultValue() *BillingFeatureFields {
	f.selection.AddField("defaultValue")
	return f
}

// UnitType selects the unitType field
func (f *BillingFeatureFields) UnitType() *BillingFeatureFields {
	f.selection.AddField("unitType")
	return f
}

// FeatureType selects the featureType field
func (f *BillingFeatureFields) FeatureType() *BillingFeatureFields {
	f.selection.AddField("featureType")
	return f
}

// SortOrder selects the sortOrder field
func (f *BillingFeatureFields) SortOrder() *BillingFeatureFields {
	f.selection.AddField("sortOrder")
	return f
}

// Description selects the description field
func (f *BillingFeatureFields) Description() *BillingFeatureFields {
	f.selection.AddField("description")
	return f
}

// BillingPlanFeatures selects the billingPlanFeatures field with nested selection
func (f *BillingFeatureFields) BillingPlanFeatures(selector func(*BillingPlanFeatureFields)) *BillingFeatureFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanFeatureFields(child))
	}
	f.selection.AddChild("billingPlanFeatures", child)
	return f
}

// CworkspaceFeatureLimits selects the cworkspaceFeatureLimits field with nested selection
func (f *BillingFeatureFields) CworkspaceFeatureLimits(selector func(*CWorkspaceFeatureLimitFields)) *BillingFeatureFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewCWorkspaceFeatureLimitFields(child))
	}
	f.selection.AddChild("cworkspaceFeatureLimits", child)
	return f
}
