// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// ChatbotToolEdgeFields provides type-safe field selection for ChatbotToolEdge
type ChatbotToolEdgeFields struct {
	selection *builder.FieldSelection
}

// NewChatbotToolEdgeFields creates a new ChatbotToolEdgeFields selector
func NewChatbotToolEdgeFields(selection *builder.FieldSelection) *ChatbotToolEdgeFields {
	return &ChatbotToolEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ChatbotToolEdgeFields) Node(selector func(*ChatbotToolFields)) *ChatbotToolEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotToolFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ChatbotToolEdgeFields) Cursor() *ChatbotToolEdgeFields {
	f.selection.AddField("cursor")
	return f
}
