// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// BillingPlanFeatureConnectionFields provides type-safe field selection for BillingPlanFeatureConnection
type BillingPlanFeatureConnectionFields struct {
	selection *builder.FieldSelection
}

// NewBillingPlanFeatureConnectionFields creates a new BillingPlanFeatureConnectionFields selector
func NewBillingPlanFeatureConnectionFields(selection *builder.FieldSelection) *BillingPlanFeatureConnectionFields {
	return &BillingPlanFeatureConnectionFields{selection: selection}
}

// Edges selects the edges field with nested selection
func (f *BillingPlanFeatureConnectionFields) Edges(selector func(*BillingPlanFeatureEdgeFields)) *BillingPlanFeatureConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewBillingPlanFeatureEdgeFields(child))
	}
	f.selection.AddChild("edges", child)
	return f
}

// PageInfo selects the pageInfo field with nested selection
func (f *BillingPlanFeatureConnectionFields) PageInfo(selector func(*PageInfoFields)) *BillingPlanFeatureConnectionFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewPageInfoFields(child))
	}
	f.selection.AddChild("pageInfo", child)
	return f
}

// TotalCount selects the totalCount field
func (f *BillingPlanFeatureConnectionFields) TotalCount() *BillingPlanFeatureConnectionFields {
	f.selection.AddField("totalCount")
	return f
}
