// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// ChatbotUserEdgeFields provides type-safe field selection for ChatbotUserEdge
type ChatbotUserEdgeFields struct {
	selection *builder.FieldSelection
}

// NewChatbotUserEdgeFields creates a new ChatbotUserEdgeFields selector
func NewChatbotUserEdgeFields(selection *builder.FieldSelection) *ChatbotUserEdgeFields {
	return &ChatbotUserEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ChatbotUserEdgeFields) Node(selector func(*ChatbotUserFields)) *ChatbotUserEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChatbotUserFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ChatbotUserEdgeFields) Cursor() *ChatbotUserEdgeFields {
	f.selection.AddField("cursor")
	return f
}
