// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// MessageFields provides type-safe field selection for Message
type MessageFields struct {
	selection *builder.FieldSelection
}

// NewMessageFields creates a new MessageFields selector
func NewMessageFields(selection *builder.FieldSelection) *MessageFields {
	return &MessageFields{selection: selection}
}

// ID selects the id field
func (f *MessageFields) ID() *MessageFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *MessageFields) CreatedAt() *MessageFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *MessageFields) UpdatedAt() *MessageFields {
	f.selection.AddField("updatedAt")
	return f
}

// Role selects the role field
func (f *MessageFields) Role() *MessageFields {
	f.selection.AddField("role")
	return f
}

// Msgid selects the msgid field
func (f *MessageFields) Msgid() *MessageFields {
	f.selection.AddField("msgid")
	return f
}

// Content selects the content field
func (f *MessageFields) Content() *MessageFields {
	f.selection.AddField("content")
	return f
}

// Parts selects the parts field
func (f *MessageFields) Parts() *MessageFields {
	f.selection.AddField("parts")
	return f
}

// PromptTokens selects the promptTokens field
func (f *MessageFields) PromptTokens() *MessageFields {
	f.selection.AddField("promptTokens")
	return f
}

// CompletionTokens selects the completionTokens field
func (f *MessageFields) CompletionTokens() *MessageFields {
	f.selection.AddField("completionTokens")
	return f
}

// TotalTokens selects the totalTokens field
func (f *MessageFields) TotalTokens() *MessageFields {
	f.selection.AddField("totalTokens")
	return f
}

// UserID selects the userID field
func (f *MessageFields) UserID() *MessageFields {
	f.selection.AddField("userID")
	return f
}

// ChannelID selects the channelID field
func (f *MessageFields) ChannelID() *MessageFields {
	f.selection.AddField("channelID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *MessageFields) WorkspaceID() *MessageFields {
	f.selection.AddField("workspaceID")
	return f
}

// ChatbotID selects the chatbotID field
func (f *MessageFields) ChatbotID() *MessageFields {
	f.selection.AddField("chatbotID")
	return f
}

// Channel selects the channel field with nested selection
func (f *MessageFields) Channel(selector func(*ChannelFields)) *MessageFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChannelFields(child))
	}
	f.selection.AddChild("channel", child)
	return f
}

// User selects the user field with nested selection
func (f *MessageFields) User(selector func(*UserFields)) *MessageFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewUserFields(child))
	}
	f.selection.AddChild("user", child)
	return f
}
