// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// ChannelUserEdgeFields provides type-safe field selection for ChannelUserEdge
type ChannelUserEdgeFields struct {
	selection *builder.FieldSelection
}

// NewChannelUserEdgeFields creates a new ChannelUserEdgeFields selector
func NewChannelUserEdgeFields(selection *builder.FieldSelection) *ChannelUserEdgeFields {
	return &ChannelUserEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *ChannelUserEdgeFields) Node(selector func(*ChannelUserFields)) *ChannelUserEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewChannelUserFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *ChannelUserEdgeFields) Cursor() *ChannelUserEdgeFields {
	f.selection.AddField("cursor")
	return f
}
