// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// CWorkspaceSubEdgeFields provides type-safe field selection for CWorkspaceSubEdge
type CWorkspaceSubEdgeFields struct {
	selection *builder.FieldSelection
}

// NewCWorkspaceSubEdgeFields creates a new CWorkspaceSubEdgeFields selector
func NewCWorkspaceSubEdgeFields(selection *builder.FieldSelection) *CWorkspaceSubEdgeFields {
	return &CWorkspaceSubEdgeFields{selection: selection}
}

// Node selects the node field with nested selection
func (f *CWorkspaceSubEdgeFields) Node(selector func(*CWorkspaceSubFields)) *CWorkspaceSubEdgeFields {
	child := builder.NewFieldSelection()
	if selector != nil {
		selector(NewCWorkspaceSubFields(child))
	}
	f.selection.AddChild("node", child)
	return f
}

// Cursor selects the cursor field
func (f *CWorkspaceSubEdgeFields) Cursor() *CWorkspaceSubEdgeFields {
	f.selection.AddField("cursor")
	return f
}
