// Code generated by gqlcustom. DO NOT EDIT.

package fields

import (
	"sdkexample/sdk/builder"
)

// GuestFields provides type-safe field selection for Guest
type GuestFields struct {
	selection *builder.FieldSelection
}

// NewGuestFields creates a new GuestFields selector
func NewGuestFields(selection *builder.FieldSelection) *GuestFields {
	return &GuestFields{selection: selection}
}

// ID selects the id field
func (f *GuestFields) ID() *GuestFields {
	f.selection.AddField("id")
	return f
}

// CreatedAt selects the createdAt field
func (f *GuestFields) CreatedAt() *GuestFields {
	f.selection.AddField("createdAt")
	return f
}

// UpdatedAt selects the updatedAt field
func (f *GuestFields) UpdatedAt() *GuestFields {
	f.selection.AddField("updatedAt")
	return f
}

// ExtUserID selects the extUserID field
func (f *GuestFields) ExtUserID() *GuestFields {
	f.selection.AddField("extUserID")
	return f
}

// FirstName selects the firstName field
func (f *GuestFields) FirstName() *GuestFields {
	f.selection.AddField("firstName")
	return f
}

// LastName selects the lastName field
func (f *GuestFields) LastName() *GuestFields {
	f.selection.AddField("lastName")
	return f
}

// Email selects the email field
func (f *GuestFields) Email() *GuestFields {
	f.selection.AddField("email")
	return f
}

// IP selects the ip field
func (f *GuestFields) IP() *GuestFields {
	f.selection.AddField("ip")
	return f
}

// ChatbotID selects the chatbotID field
func (f *GuestFields) ChatbotID() *GuestFields {
	f.selection.AddField("chatbotID")
	return f
}

// WorkspaceID selects the workspaceID field
func (f *GuestFields) WorkspaceID() *GuestFields {
	f.selection.AddField("workspaceID")
	return f
}
