// Code generated by gqlkit. DO NOT EDIT.

import { GraphQLClient } from "../builder";
import { PingBuilder } from "./ping";
import { TodoBuilder } from "./todo";
import { TodosBuilder } from "./todos";
import { TodosConnectionBuilder } from "./todos-connection";
import { UserBuilder } from "./user";
import { UsersBuilder } from "./users";
import { SearchBuilder } from "./search";
import { EchoBuilder } from "./echo";
import { SumBuilder } from "./sum";

/** QueryRoot is the entry point for querys */
export class QueryRoot {
  private client: GraphQLClient;

  constructor(client: GraphQLClient) {
    this.client = client;
  }

  ping(): PingBuilder {
    return new PingBuilder(this.client);
  }

  todo(): TodoBuilder {
    return new TodoBuilder(this.client);
  }

  todos(): TodosBuilder {
    return new TodosBuilder(this.client);
  }

  todosConnection(): TodosConnectionBuilder {
    return new TodosConnectionBuilder(this.client);
  }

  user(): UserBuilder {
    return new UserBuilder(this.client);
  }

  users(): UsersBuilder {
    return new UsersBuilder(this.client);
  }

  search(): SearchBuilder {
    return new SearchBuilder(this.client);
  }

  echo(): EchoBuilder {
    return new EchoBuilder(this.client);
  }

  sum(): SumBuilder {
    return new SumBuilder(this.client);
  }
}
