// Code generated by gqlkit. DO NOT EDIT.

import { BaseBuilder, GraphQLClient } from "../builder";
import type { JSON } from "../scalars";

/** ServerInfoBuilder builds a query for serverInfo */
export class ServerInfoBuilder {
  private builder: BaseBuilder;

  constructor(client: GraphQLClient) {
    this.builder = new BaseBuilder(client, "query", "ServerInfo", "serverInfo");
  }

  /** Execute runs the query and returns the result */
  async execute(): Promise<any> {
    const query = this.builder.buildQuery();
    const variables = this.builder.getVariables();

    const response = await this.builder
      .getClient()
      .execute<{ serverInfo: any }>(query, variables);

    return response.serverInfo;
  }

  /** ExecuteRaw runs the query and returns the raw response */
  async executeRaw(): Promise<Record<string, unknown>> {
    return await this.builder.executeRaw();
  }
}
