package clientgen

import (
	"bytes"
	"fmt"
	"gqlcustom/pkg/util"
	"sort"
	"strings"

	"github.com/vektah/gqlparser/v2/ast"
)

const defaultBuilderPkg = "gqlcustom/sdk/builder"

// FieldSelectorData is the template data for a single type's field selector
type FieldSelectorData struct {
	BuilderPkgImport string // full import path, e.g. "gqlcustom/pkg/builder"
	BuilderPkgName   string // package identifier in code, e.g. "builder"
	TypeName         string
	SelectorName     string
	Fields           []FieldSelField
}

// FieldSelField describes one field on a field selector
type FieldSelField struct {
	FieldName      string
	MethodName     string
	IsObject       bool
	NestedSelector string
}

// getBaseTypeName returns the named type after unwrapping List and NonNull
func getBaseTypeName(t *ast.Type) string {
	if t == nil {
		return ""
	}
	if t.Elem != nil {
		return getBaseTypeName(t.Elem)
	}
	return t.NamedType
}

// isObjectType returns true if the type is an Object or Interface (needs nested selection)
func isObjectType(schema *ast.Schema, t *ast.Type) bool {
	name := getBaseTypeName(t)
	if name == "" {
		return false
	}
	def := schema.Types[name]
	if def == nil {
		return false
	}
	return def.Kind == ast.Object || def.Kind == ast.Interface
}

// toSnakeCase converts PascalCase or CamelCase to snake_case
func toSnakeCase(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		b.WriteRune(r)
	}
	return strings.ToLower(b.String())
}

// getSortedObjectTypeNames returns schema object type names (excluding builtin and roots), sorted
func (g *Generator) getSortedObjectTypeNames() []string {
	var names []string
	for name, def := range g.schema.Types {
		if def.BuiltIn || strings.HasPrefix(name, "__") {
			continue
		}
		if def.Kind != ast.Object && def.Kind != ast.Interface {
			continue
		}
		if name == "Query" || name == "Mutation" || name == "Subscription" {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// buildFieldSelectorData builds template data for one object type's field selector
func (g *Generator) buildFieldSelectorData(def *ast.Definition) FieldSelectorData {
	data := FieldSelectorData{
		TypeName:     def.Name,
		SelectorName: def.Name + "Fields",
		Fields:       make([]FieldSelField, 0, len(def.Fields)),
	}

	// Builder package: prefer configured SDK package (e.g. gqlcustom/sdk) then /builder.
	rootPkg := strings.TrimSuffix(g.config.Package, "/")
	if rootPkg != "" {
		data.BuilderPkgImport = rootPkg + "/builder"
	} else {
		data.BuilderPkgImport = defaultBuilderPkg
	}
	data.BuilderPkgName = "builder"
	if idx := strings.LastIndex(data.BuilderPkgImport, "/"); idx >= 0 && idx < len(data.BuilderPkgImport)-1 {
		data.BuilderPkgName = data.BuilderPkgImport[idx+1:]
	}

	for _, field := range def.Fields {
		if strings.HasPrefix(field.Name, "__") {
			continue
		}
		baseName := getBaseTypeName(field.Type)
		isObj := isObjectType(g.schema, field.Type) && baseName != def.Name

		f := FieldSelField{
			FieldName:  field.Name,
			MethodName: util.ToPascalCase(field.Name),
			IsObject:   isObj,
		}
		if isObj {
			f.NestedSelector = baseName + "Fields"
		}
		data.Fields = append(data.Fields, f)
	}

	return data
}

// generateFieldSelectionFiles generates one file per object type in the fields directory,
// each containing a type-safe field selector based on builder.FieldSelection
func (g *Generator) generateFieldSelectionFiles() error {
	names := g.getSortedObjectTypeNames()
	for _, name := range names {
		def := g.schema.Types[name]
		if def == nil {
			continue
		}
		data := g.buildFieldSelectorData(def)
		var buf bytes.Buffer
		if err := g.templates.ExecuteTemplate(&buf, "field_selector", data); err != nil {
			return fmt.Errorf("field selector template for %s: %w", name, err)
		}
		filename := fmt.Sprintf("fields/field_%s.go", util.ToSnakeCase(name))
		content := "// Code generated by gqlcustom. DO NOT EDIT.\n\npackage fields\n\nimport (\n\t\"" + data.BuilderPkgImport + "\"\n)\n\n" + buf.String()
		if err := g.writer.WriteFile(filename, content); err != nil {
			return fmt.Errorf("write %s: %w", filename, err)
		}
	}
	return nil
}
