// Code generated by gqlkit. DO NOT EDIT.

export type Boolean = boolean;
export type Cursor = string;
export type { DateTime } from "luxon";
export type Float = number;
export type GqlString = string;
export type ID = string;
export type Int = number;
export type { JsonValue as JSON } from "type-fest";
export type Metadata = any;
