// Code generated by gqlkit. DO NOT EDIT.

export type Boolean = boolean;
export type Cursor = string;
export type DateTime = string;
export type Float = number;
export type GqlString = string;
export type ID = string;
export type Int = number;
export type JSON = any;
export type Metadata = any;
