// Code generated by gqlkit. DO NOT EDIT.

import { FieldSelection } from "../builder";

/** NodeFields provides type-safe field selection for Node */
export class NodeFields<T extends object = {}> {
  private selection: FieldSelection;

  constructor(selection: FieldSelection) {
    this.selection = selection;
  }

  id(): NodeFields<T & { id: string }> {
    this.selection.addField("id");
    return this as any;
  }
}
