// Code generated by gqlkit. DO NOT EDIT.

import { FieldSelection } from "../builder";

/** PageInfoFields provides type-safe field selection for PageInfo */
export class PageInfoFields<T extends object = {}> {
  private selection: FieldSelection;

  constructor(selection: FieldSelection) {
    this.selection = selection;
  }

  hasNextPage(): PageInfoFields<T & { hasNextPage: boolean }> {
    this.selection.addField("hasNextPage");
    return this as any;
  }

  hasPreviousPage(): PageInfoFields<T & { hasPreviousPage: boolean }> {
    this.selection.addField("hasPreviousPage");
    return this as any;
  }

  startCursor(): PageInfoFields<T & { startCursor?: string }> {
    this.selection.addField("startCursor");
    return this as any;
  }

  endCursor(): PageInfoFields<T & { endCursor?: string }> {
    this.selection.addField("endCursor");
    return this as any;
  }
}
