// Code generated by gqlkit. DO NOT EDIT.

import { FieldSelection } from "../builder";
import { UserFields } from "./user";
import type { DateTime, Metadata } from "../scalars";

/** TodoFields provides type-safe field selection for Todo */
export class TodoFields<T extends object = {}> {
  private selection: FieldSelection;

  constructor(selection: FieldSelection) {
    this.selection = selection;
  }

  id(): TodoFields<T & { id: string }> {
    this.selection.addField("id");
    return this as any;
  }

  text(): TodoFields<T & { text: string }> {
    this.selection.addField("text");
    return this as any;
  }

  done(): TodoFields<T & { done: boolean }> {
    this.selection.addField("done");
    return this as any;
  }

  priority(): TodoFields<T & { priority?: number }> {
    this.selection.addField("priority");
    return this as any;
  }

  tags(): TodoFields<T & { tags: string[] }> {
    this.selection.addField("tags");
    return this as any;
  }

  user<U extends object>(selector: (f: UserFields) => UserFields<U>): TodoFields<T & { user: U }> {
    const child = new FieldSelection();
    selector(new UserFields(child));
    this.selection.addChild("user", child);
    return this as any;
  }

  createdAt(): TodoFields<T & { createdAt: DateTime }> {
    this.selection.addField("createdAt");
    return this as any;
  }

  metadata(): TodoFields<T & { metadata?: Metadata }> {
    this.selection.addField("metadata");
    return this as any;
  }
}
