// Code generated by gqlkit. DO NOT EDIT.

import { FieldSelection } from "../builder";
import { PageInfoFields } from "./page-info";
import { TodoEdgeFields } from "./todo-edge";

/** TodoConnectionFields provides type-safe field selection for TodoConnection */
export class TodoConnectionFields<T extends object = {}> {
  private selection: FieldSelection;

  constructor(selection: FieldSelection) {
    this.selection = selection;
  }

  edges<U extends object>(selector: (f: TodoEdgeFields) => TodoEdgeFields<U>): TodoConnectionFields<T & { edges: U[] }> {
    const child = new FieldSelection();
    selector(new TodoEdgeFields(child));
    this.selection.addChild("edges", child);
    return this as any;
  }

  pageInfo<U extends object>(selector: (f: PageInfoFields) => PageInfoFields<U>): TodoConnectionFields<T & { pageInfo: U }> {
    const child = new FieldSelection();
    selector(new PageInfoFields(child));
    this.selection.addChild("pageInfo", child);
    return this as any;
  }

  totalCount(): TodoConnectionFields<T & { totalCount: number }> {
    this.selection.addField("totalCount");
    return this as any;
  }
}
