// Code generated by gqlkit. DO NOT EDIT.

import { FieldSelection } from "../builder";
import { TodoFields } from "./todo";

/** TodoEdgeFields provides type-safe field selection for TodoEdge */
export class TodoEdgeFields<T extends object = {}> {
  private selection: FieldSelection;

  constructor(selection: FieldSelection) {
    this.selection = selection;
  }

  cursor(): TodoEdgeFields<T & { cursor: string }> {
    this.selection.addField("cursor");
    return this as any;
  }

  node<U extends object>(selector: (f: TodoFields) => TodoFields<U>): TodoEdgeFields<T & { node: U }> {
    const child = new FieldSelection();
    selector(new TodoFields(child));
    this.selection.addChild("node", child);
    return this as any;
  }
}
