// Code generated by gqlkit. DO NOT EDIT.

import { FieldSelection } from "../builder";
import type { Role } from "../enums";

/** UserFields provides type-safe field selection for User */
export class UserFields<T extends object = {}> {
  private selection: FieldSelection;

  constructor(selection: FieldSelection) {
    this.selection = selection;
  }

  id(): UserFields<T & { id: string }> {
    this.selection.addField("id");
    return this as any;
  }

  name(): UserFields<T & { name: string }> {
    this.selection.addField("name");
    return this as any;
  }

  email(): UserFields<T & { email?: string }> {
    this.selection.addField("email");
    return this as any;
  }

  role(): UserFields<T & { role: Role }> {
    this.selection.addField("role");
    return this as any;
  }
}
