// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample/sdk/builder"
	"sdkexample/sdk/fields"
	"sdkexample/sdk/types"
)

// NodeBuilder builds a query for node
type NodeBuilder struct {
	*builder.BaseBuilder
}

// ID sets the id argument
func (b *NodeBuilder) ID(v string) *NodeBuilder {
	b.SetArg("id", v, "ID!")
	return b
}

// Select configures which fields to return
func (b *NodeBuilder) Select(selector func(*fields.NodeFields)) *NodeBuilder {
	selector(fields.NewNodeFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *NodeBuilder) Execute(ctx context.Context) (*types.Node, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result *types.Node `json:"node"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
