// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample/sdk/builder"
	"sdkexample/sdk/fields"
	"sdkexample/sdk/types"
)

// WorkspaceDetailBuilder builds a query for workspaceDetail
type WorkspaceDetailBuilder struct {
	*builder.BaseBuilder
}

// Select configures which fields to return
func (b *WorkspaceDetailBuilder) Select(selector func(*fields.WorkspaceDetailFields)) *WorkspaceDetailBuilder {
	selector(fields.NewWorkspaceDetailFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *WorkspaceDetailBuilder) Execute(ctx context.Context) (*types.WorkspaceDetail, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result *types.WorkspaceDetail `json:"workspaceDetail"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
