// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample/sdk/builder"
	"sdkexample/sdk/fields"
	"sdkexample/sdk/inputs"
	"sdkexample/sdk/scalars"
	"sdkexample/sdk/types"
)

// LeadsBuilder builds a query for leads
type LeadsBuilder struct {
	*builder.BaseBuilder
}

// After sets the after argument
func (b *LeadsBuilder) After(v *scalars.Cursor) *LeadsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *LeadsBuilder) First(v *int) *LeadsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *LeadsBuilder) Before(v *scalars.Cursor) *LeadsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *LeadsBuilder) Last(v *int) *LeadsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *LeadsBuilder) OrderBy(v []inputs.LeadOrder) *LeadsBuilder {
	b.SetArg("orderBy", v, "[LeadOrder!]")
	return b
}

// Where sets the where argument
func (b *LeadsBuilder) Where(v *inputs.LeadWhereInput) *LeadsBuilder {
	b.SetArg("where", v, "LeadWhereInput")
	return b
}

// Select configures which fields to return
func (b *LeadsBuilder) Select(selector func(*fields.LeadConnectionFields)) *LeadsBuilder {
	selector(fields.NewLeadConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *LeadsBuilder) Execute(ctx context.Context) (types.LeadConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.LeadConnection `json:"leads"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.LeadConnection{}, err
	}

	return response.Result, nil
}
