// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample/sdk/builder"
	"sdkexample/sdk/fields"
	"sdkexample/sdk/types"
)

// NodesBuilder builds a query for nodes
type NodesBuilder struct {
	*builder.BaseBuilder
}

// Ids sets the ids argument
func (b *NodesBuilder) Ids(v []string) *NodesBuilder {
	b.SetArg("ids", v, "[ID!]!")
	return b
}

// Select configures which fields to return
func (b *NodesBuilder) Select(selector func(*fields.NodeFields)) *NodesBuilder {
	selector(fields.NewNodeFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *NodesBuilder) Execute(ctx context.Context) ([]*types.Node, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []*types.Node `json:"nodes"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
