// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample/sdk/builder"
	"sdkexample/sdk/fields"
	"sdkexample/sdk/types"
)

// ItemGroupSourcesSummaryBuilder builds a query for itemGroupSourcesSummary
type ItemGroupSourcesSummaryBuilder struct {
	*builder.BaseBuilder
}

// ID sets the id argument
func (b *ItemGroupSourcesSummaryBuilder) ID(v string) *ItemGroupSourcesSummaryBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// Select configures which fields to return
func (b *ItemGroupSourcesSummaryBuilder) Select(selector func(*fields.ItemGroupSourceSummaryFields)) *ItemGroupSourcesSummaryBuilder {
	selector(fields.NewItemGroupSourceSummaryFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ItemGroupSourcesSummaryBuilder) Execute(ctx context.Context) ([]types.ItemGroupSourceSummary, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []types.ItemGroupSourceSummary `json:"itemGroupSourcesSummary"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
