// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample/sdk/builder"
	"sdkexample/sdk/fields"
	"sdkexample/sdk/inputs"
	"sdkexample/sdk/types"
)

// IChatbotBuilder builds a query for iChatbot
type IChatbotBuilder struct {
	*builder.BaseBuilder
}

// ID sets the id argument
func (b *IChatbotBuilder) ID(v string) *IChatbotBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// Input sets the input argument
func (b *IChatbotBuilder) Input(v *inputs.IChatbotGetInput) *IChatbotBuilder {
	b.SetArg("input", v, "IChatbotGetInput")
	return b
}

// Select configures which fields to return
func (b *IChatbotBuilder) Select(selector func(*fields.ChatbotFields)) *IChatbotBuilder {
	selector(fields.NewChatbotFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *IChatbotBuilder) Execute(ctx context.Context) (types.Chatbot, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.Chatbot `json:"iChatbot"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.Chatbot{}, err
	}

	return response.Result, nil
}
