// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample/sdk/builder"
	"sdkexample/sdk/fields"
	"sdkexample/sdk/inputs"
	"sdkexample/sdk/scalars"
	"sdkexample/sdk/types"
)

// FuncToolsBuilder builds a query for funcTools
type FuncToolsBuilder struct {
	*builder.BaseBuilder
}

// After sets the after argument
func (b *FuncToolsBuilder) After(v *scalars.Cursor) *FuncToolsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *FuncToolsBuilder) First(v *int) *FuncToolsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *FuncToolsBuilder) Before(v *scalars.Cursor) *FuncToolsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *FuncToolsBuilder) Last(v *int) *FuncToolsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *FuncToolsBuilder) OrderBy(v []inputs.FuncToolOrder) *FuncToolsBuilder {
	b.SetArg("orderBy", v, "[FuncToolOrder!]")
	return b
}

// Where sets the where argument
func (b *FuncToolsBuilder) Where(v *inputs.FuncToolWhereInput) *FuncToolsBuilder {
	b.SetArg("where", v, "FuncToolWhereInput")
	return b
}

// Select configures which fields to return
func (b *FuncToolsBuilder) Select(selector func(*fields.FuncToolConnectionFields)) *FuncToolsBuilder {
	selector(fields.NewFuncToolConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *FuncToolsBuilder) Execute(ctx context.Context) (types.FuncToolConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.FuncToolConnection `json:"funcTools"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.FuncToolConnection{}, err
	}

	return response.Result, nil
}
