// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample/sdk/builder"
	"sdkexample/sdk/fields"
	"sdkexample/sdk/types"
)

// ItemAiSearchBuilder builds a query for itemAiSearch
type ItemAiSearchBuilder struct {
	*builder.BaseBuilder
}

// ItemGroupID sets the itemGroupID argument
func (b *ItemAiSearchBuilder) ItemGroupID(v string) *ItemAiSearchBuilder {
	b.SetArg("itemGroupID", v, "ID!")
	return b
}

// Search sets the search argument
func (b *ItemAiSearchBuilder) Search(v string) *ItemAiSearchBuilder {
	b.SetArg("search", v, "String!")
	return b
}

// Select configures which fields to return
func (b *ItemAiSearchBuilder) Select(selector func(*fields.ItemFields)) *ItemAiSearchBuilder {
	selector(fields.NewItemFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ItemAiSearchBuilder) Execute(ctx context.Context) ([]types.Item, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []types.Item `json:"itemAiSearch"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
