// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample/sdk/builder"
	"sdkexample/sdk/fields"
	"sdkexample/sdk/types"
)

// BillingCustomPlansBuilder builds a query for billingCustomPlans
type BillingCustomPlansBuilder struct {
	*builder.BaseBuilder
}

// Select configures which fields to return
func (b *BillingCustomPlansBuilder) Select(selector func(*fields.BillingPlanFields)) *BillingCustomPlansBuilder {
	selector(fields.NewBillingPlanFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *BillingCustomPlansBuilder) Execute(ctx context.Context) ([]*types.BillingPlan, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []*types.BillingPlan `json:"billingCustomPlans"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
