// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample/sdk/builder"
	"sdkexample/sdk/fields"
	"sdkexample/sdk/types"
)

// IAiModelBuilder builds a query for iAiModel
type IAiModelBuilder struct {
	*builder.BaseBuilder
}

// ID sets the id argument
func (b *IAiModelBuilder) ID(v string) *IAiModelBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// Select configures which fields to return
func (b *IAiModelBuilder) Select(selector func(*fields.AiModelFields)) *IAiModelBuilder {
	selector(fields.NewAiModelFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *IAiModelBuilder) Execute(ctx context.Context) (types.AiModel, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.AiModel `json:"iAiModel"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.AiModel{}, err
	}

	return response.Result, nil
}
