// Code generated by gqlcustom. DO NOT EDIT.

package queries

import (
	"context"
	"sdkexample/sdk/builder"
	"sdkexample/sdk/fields"
	"sdkexample/sdk/inputs"
	"sdkexample/sdk/scalars"
	"sdkexample/sdk/types"
)

// ChatbotsBuilder builds a query for chatbots
type ChatbotsBuilder struct {
	*builder.BaseBuilder
}

// After sets the after argument
func (b *ChatbotsBuilder) After(v *scalars.Cursor) *ChatbotsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ChatbotsBuilder) First(v *int) *ChatbotsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ChatbotsBuilder) Before(v *scalars.Cursor) *ChatbotsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ChatbotsBuilder) Last(v *int) *ChatbotsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ChatbotsBuilder) OrderBy(v []inputs.ChatbotOrder) *ChatbotsBuilder {
	b.SetArg("orderBy", v, "[ChatbotOrder!]")
	return b
}

// Where sets the where argument
func (b *ChatbotsBuilder) Where(v *inputs.ChatbotWhereInput) *ChatbotsBuilder {
	b.SetArg("where", v, "ChatbotWhereInput")
	return b
}

// Select configures which fields to return
func (b *ChatbotsBuilder) Select(selector func(*fields.ChatbotConnectionFields)) *ChatbotsBuilder {
	selector(fields.NewChatbotConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ChatbotsBuilder) Execute(ctx context.Context) (types.ChatbotConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.ChatbotConnection `json:"chatbots"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.ChatbotConnection{}, err
	}

	return response.Result, nil
}
