version: 2

project_name: gqlkit

git:
  tag_sort: -version:refname
  prerelease_suffix: "-"
  ignore_tags:
    - "gqlkit-sdl/v*"

monorepo:
  tag_prefix: gqlkit/

builds:
  - id: gqlkit
    main: ./cmd/cli
    binary: gqlkit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: gqlkit
    builds:
      - gqlkit
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: khanakia
    name: gqlkit
