// Code generated by gqlkit. DO NOT EDIT.

import type { Role } from "../enums";



export interface Node {
  id: string;
}

export interface PageInfo {
  hasNextPage: boolean;
  hasPreviousPage: boolean;
  startCursor?: string;
  endCursor?: string;
}

export interface Todo {
  id: string;
  text: string;
  done: boolean;
  priority?: number;
  tags: string[];
  user: User;
}

export interface TodoConnection {
  edges: TodoEdge[];
  pageInfo: PageInfo;
  totalCount: number;
}

export interface TodoEdge {
  cursor: string;
  node: Todo;
}

export interface User {
  id: string;
  name: string;
  email?: string;
  role: Role;
}
