// Code generated by gqlkit. DO NOT EDIT.



export interface NewTodo {
  text: string;
  userId: string;
  priority?: number;
  tags?: string[];
}

export interface PaginationInput {
  limit: number;
  offset: number;
}

export interface TodoFilter {
  textContains?: string;
  done?: boolean;
  minPriority?: number;
  hasTag?: string;
}

export interface UpdateTodoInput {
  text?: string;
  done?: boolean;
  priority?: number;
  tags?: string[];
}
