// Package graph contains the resolver implementation for the mock GraphQL API.
// This file is hand-written (not regenerated by gqlgen) and holds the Resolver
// struct, seed data initialization, and helper functions for filtering.
package graph

import (
	"mockapi/graph/model"
	"strings"
)

// Resolver is the root resolver that implements the gqlgen ResolverRoot interface.
// It holds all application state in-memory: a list of todos and users.
// Data is lazily seeded on the first query via seedData().
// Not safe for concurrent use (acceptable for a single-user test/mock API).
type Resolver struct {
	todos []*model.Todo
	users []*model.User
}

// seedData populates the in-memory store with default users and todos if they
// have not been initialized yet. Called lazily by resolvers on first access.
// Seeds two users (Alice as User, Bob as Admin) and two demo todos.
func (r *Resolver) seedData() {
	if r.users == nil {
		r.users = []*model.User{
			{ID: "1", Name: "Alice", Role: model.RoleUser},
			{ID: "2", Name: "Bob", Role: model.RoleAdmin},
		}
	}
	if r.todos == nil {
		r.todos = []*model.Todo{
			{
				ID:        "1",
				Text:      "Try the ping query",
				Done:      false,
				Tags:      []string{"demo", "ping"},
				User:      r.users[0],
				CreatedAt: "2025-01-15T09:30:00Z",
				Metadata:  map[string]any{"source": "seed", "priority_label": "low"},
			},
			{
				ID:        "2",
				Text:      "Create your first todo",
				Done:      false,
				Tags:      []string{"demo"},
				User:      r.users[1],
				CreatedAt: "2025-01-16T14:00:00Z",
			},
		}
	}
}

// matchesTodoFilter checks whether a todo satisfies all criteria in the given filter.
// Returns true if filter is nil (no filtering). Each non-nil filter field is applied
// as an AND condition: text substring match, done status, minimum priority, and tag membership.
func matchesTodoFilter(t *model.Todo, f *model.TodoFilter) bool {
	if f == nil {
		return true
	}
	if f.TextContains != nil && !containsIgnoreCase(t.Text, *f.TextContains) {
		return false
	}
	if f.Done != nil && t.Done != *f.Done {
		return false
	}
	// MinPriority requires the todo to have a priority set and >= the threshold.
	if f.MinPriority != nil {
		if t.Priority == nil || *t.Priority < *f.MinPriority {
			return false
		}
	}
	// HasTag requires at least one of the todo's tags to match exactly.
	if f.HasTag != nil {
		found := false
		for _, tag := range t.Tags {
			if tag == *f.HasTag {
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	return true
}

// containsIgnoreCase performs a case-insensitive substring check.
// Returns true if substr is empty (matches everything).
func containsIgnoreCase(s, substr string) bool {
	if substr == "" {
		return true
	}
	return strings.Contains(strings.ToLower(s), strings.ToLower(substr))
}
