package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code
// will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87
//
// NOTE: While gqlgen manages the function stubs, the resolver bodies are hand-written.
// This file implements all query and mutation resolvers for the mock API:
//   - Mutations: CreateTodo, UpdateTodo, DeleteTodo, UpsertUser, CompleteAllTodos
//   - Queries: Ping, Todo, Todos (with filter + offset pagination),
//     TodosConnection (cursor-based), User, Users, Search, Echo, Sum

import (
	"context"
	"fmt"
	"mockapi/graph/model"
)

// CreateTodo creates a new todo in the in-memory store.
// It assigns a sequential string ID, links the specified user (if found),
// and defaults Done to false. Returns the newly created todo.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	// Ensure seed data exists before any mutation.
	if r.users == nil || len(r.users) == 0 {
		r.seedData()
	}

	// Generate a simple sequential ID based on current slice length.
	id := fmt.Sprintf("%d", len(r.todos)+1)
	todo := &model.Todo{
		ID:       id,
		Text:     input.Text,
		Done:     false,
		Priority: input.Priority,
		Tags:     input.Tags,
	}

	// Look up the user by ID and attach to the todo if found.
	for _, u := range r.users {
		if u.ID == input.UserID {
			todo.User = u
			break
		}
	}

	r.todos = append(r.todos, todo)
	return todo, nil
}

// UpdateTodo performs a partial update on an existing todo identified by ID.
// Only non-nil fields in the input are applied (patch semantics).
// Returns nil if the todo is not found (no error).
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, input model.UpdateTodoInput) (*model.Todo, error) {
	if r.todos == nil {
		r.seedData()
	}
	for _, t := range r.todos {
		if t.ID == id {
			// Apply only the fields that were explicitly provided.
			if input.Text != nil {
				t.Text = *input.Text
			}
			if input.Done != nil {
				t.Done = *input.Done
			}
			if input.Priority != nil {
				t.Priority = input.Priority
			}
			if input.Tags != nil && len(input.Tags) > 0 {
				t.Tags = input.Tags
			}
			return t, nil
		}
	}
	return nil, nil
}

// DeleteTodo removes a todo by ID from the in-memory store.
// Returns true if a todo was found and deleted, false otherwise.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (bool, error) {
	if r.todos == nil {
		r.seedData()
	}
	for i, t := range r.todos {
		if t.ID == id {
			// Remove by re-slicing (order-preserving delete).
			r.todos = append(r.todos[:i], r.todos[i+1:]...)
			return true, nil
		}
	}
	return false, nil
}

// UpsertUser creates or updates a user. If an ID is provided and matches an
// existing user, that user's fields are updated in place. Otherwise, a new
// user is created with a sequential ID and defaults to the User role.
func (r *mutationResolver) UpsertUser(ctx context.Context, id *string, name string, email *string, role *model.Role) (*model.User, error) {
	if r.users == nil {
		r.seedData()
	}

	// Update path: find existing user by ID and overwrite fields.
	if id != nil {
		for _, u := range r.users {
			if u.ID == *id {
				u.Name = name
				u.Email = email
				if role != nil {
					u.Role = *role
				}
				return u, nil
			}
		}
	}

	// Create path: no matching ID found (or no ID provided).
	newID := fmt.Sprintf("%d", len(r.users)+1)
	newRole := model.RoleUser
	if role != nil {
		newRole = *role
	}
	u := &model.User{
		ID:    newID,
		Name:  name,
		Email: email,
		Role:  newRole,
	}
	r.users = append(r.users, u)
	return u, nil
}

// CompleteAllTodos marks every incomplete todo as done.
// Returns the count of todos that were actually changed.
func (r *mutationResolver) CompleteAllTodos(ctx context.Context) (int32, error) {
	if r.todos == nil {
		r.seedData()
	}
	var count int32
	for _, t := range r.todos {
		if !t.Done {
			t.Done = true
			count++
		}
	}
	return count, nil
}

// Ping is a simple health-check query that returns a static response.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong from gqlgenapi", nil
}

// Todo fetches a single todo by its ID. Returns nil (not an error) if not found.
func (r *queryResolver) Todo(ctx context.Context, id string) (*model.Todo, error) {
	if r.todos == nil {
		r.seedData()
	}
	for _, t := range r.todos {
		if t.ID == id {
			return t, nil
		}
	}
	return nil, nil
}

// Todos returns a filtered, paginated list of todos.
// Filtering is applied first via matchesTodoFilter, then offset-based pagination
// is applied using the optional PaginationInput (offset + limit).
func (r *queryResolver) Todos(ctx context.Context, filter *model.TodoFilter, pagination *model.PaginationInput) ([]*model.Todo, error) {
	if r.todos == nil {
		r.seedData()
	}
	// Phase 1: collect all todos matching the filter criteria.
	var out []*model.Todo
	for _, t := range r.todos {
		if matchesTodoFilter(t, filter) {
			out = append(out, t)
		}
	}
	// Phase 2: apply offset-based pagination.
	// Default to returning all results if no pagination is specified.
	start := 0
	limit := len(out)
	if pagination != nil {
		if pagination.Offset > 0 && int(pagination.Offset) < len(out) {
			start = int(pagination.Offset)
		}
		if pagination.Limit > 0 && int(pagination.Limit) < limit {
			limit = int(pagination.Limit)
		}
	}
	if start > len(out) {
		return []*model.Todo{}, nil
	}
	end := start + limit
	if end > len(out) {
		end = len(out)
	}
	return out[start:end], nil
}

// TodosConnection wraps the Todos query result in a Relay-style connection type
// with edges, cursors, and pageInfo. Cursors are synthetic ("cursor-<id>").
// Note: hasNextPage/hasPreviousPage are always false in this mock implementation.
func (r *queryResolver) TodosConnection(ctx context.Context, filter *model.TodoFilter, pagination *model.PaginationInput) (*model.TodoConnection, error) {
	// Reuse the Todos resolver for filtering and pagination logic.
	items, err := r.Todos(ctx, filter, pagination)
	if err != nil {
		return nil, err
	}
	// Wrap each todo in an edge with a synthetic cursor string.
	edges := make([]*model.TodoEdge, len(items))
	for i, t := range items {
		cursor := fmt.Sprintf("cursor-%s", t.ID)
		edges[i] = &model.TodoEdge{
			Cursor: cursor,
			Node:   t,
		}
	}
	// Build pageInfo with start/end cursors from the edge boundaries.
	var startCursor, endCursor *string
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}
	conn := &model.TodoConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     false,
			HasPreviousPage: false,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: int32(len(items)),
	}
	return conn, nil
}

// User fetches a single user by ID. Returns nil (not an error) if not found.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	if r.users == nil {
		r.seedData()
	}
	for _, u := range r.users {
		if u.ID == id {
			return u, nil
		}
	}
	return nil, nil
}

// Users returns all users in the in-memory store.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	if r.users == nil {
		r.seedData()
	}
	return r.users, nil
}

// Search performs a case-insensitive substring search across both todos (by text)
// and users (by name). Returns a union type (SearchResult) containing mixed results.
// An empty term matches all items.
func (r *queryResolver) Search(ctx context.Context, term string) ([]model.SearchResult, error) {
	if r.users == nil || r.todos == nil {
		r.seedData()
	}
	var results []model.SearchResult
	// Search todos by text content.
	for _, t := range r.todos {
		if term == "" || containsIgnoreCase(t.Text, term) {
			results = append(results, t)
		}
	}
	// Search users by name.
	for _, u := range r.users {
		if term == "" || containsIgnoreCase(u.Name, term) {
			results = append(results, u)
		}
	}
	return results, nil
}

// Echo is a simple pass-through query that returns the input message unchanged.
// Useful for testing string argument handling in GraphQL clients.
func (r *queryResolver) Echo(ctx context.Context, message string) (string, error) {
	return message, nil
}

// Sum returns the arithmetic sum of two integers.
// Useful for testing scalar argument handling in GraphQL clients.
func (r *queryResolver) Sum(ctx context.Context, a int32, b int32) (int32, error) {
	return a + b, nil
}

// Mutation returns the MutationResolver implementation, wrapping the shared Resolver.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns the QueryResolver implementation, wrapping the shared Resolver.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// mutationResolver embeds Resolver to implement MutationResolver.
type mutationResolver struct{ *Resolver }

// queryResolver embeds Resolver to implement QueryResolver.
type queryResolver struct{ *Resolver }

